/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */
import { useMutation, useQuery } from "@tanstack/vue-query";
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType,
} from "@tanstack/vue-query";

import { computed, unref } from "vue";
import type { MaybeRef } from "vue";

import type {
  ApplicationDto,
  BazarrWebhookPayload,
  GetApiTimelineParams,
  LibraryStats,
  LidarrWebhookPayload,
  MeDto,
  PostApiApplicationsBody,
  RadarrWebhookPayload,
  SeerrWebhookPayload,
  SonarrWebhookPayload,
  TimelinePageDto,
  Uuid,
} from "../model";

import { customInstance } from "../axios-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary List Applications
 */
export const getApiApplications = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ApplicationDto[]>(
    { url: `/api/applications`, method: "GET", signal },
    options,
  );
};

export const getGetApiApplicationsQueryKey = () => {
  return ["api", "applications"] as const;
};

export const getGetApiApplicationsQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiApplications>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getApiApplications>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetApiApplicationsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiApplications>>
  > = ({ signal }) => getApiApplications(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiApplications>>,
    TError,
    TData
  >;
};

export type GetApiApplicationsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiApplications>>
>;
export type GetApiApplicationsQueryError = unknown;

/**
 * @summary List Applications
 */

export function useGetApiApplications<
  TData = Awaited<ReturnType<typeof getApiApplications>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiApplications>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiApplicationsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

/**
 * @summary Create Application
 */
export const postApiApplications = (
  postApiApplicationsBody: MaybeRef<PostApiApplicationsBody>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  postApiApplicationsBody = unref(postApiApplicationsBody);
  const formData = new FormData();
  if (postApiApplicationsBody.name !== null) {
    formData.append("name", postApiApplicationsBody.name);
  }
  if (postApiApplicationsBody.category !== null) {
    formData.append("category", postApiApplicationsBody.category);
  }
  if (postApiApplicationsBody.description !== null) {
    formData.append("description", postApiApplicationsBody.description);
  }
  if (postApiApplicationsBody.url !== null) {
    formData.append("url", postApiApplicationsBody.url);
  }
  formData.append(
    "requiresVpn",
    postApiApplicationsBody.requiresVpn.toString(),
  );
  if (postApiApplicationsBody.logo !== null) {
    formData.append("logo", postApiApplicationsBody.logo);
  }

  return customInstance<unknown>(
    {
      url: `/api/applications`,
      method: "POST",
      headers: { "Content-Type": "multipart/form-data" },
      data: formData,
      signal,
    },
    options,
  );
};

export const getPostApiApplicationsMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiApplications>>,
    TError,
    { data: PostApiApplicationsBody },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiApplications>>,
  TError,
  { data: PostApiApplicationsBody },
  TContext
> => {
  const mutationKey = ["postApiApplications"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiApplications>>,
    { data: PostApiApplicationsBody }
  > = (props) => {
    const { data } = props ?? {};

    return postApiApplications(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiApplicationsMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiApplications>>
>;
export type PostApiApplicationsMutationBody = PostApiApplicationsBody;
export type PostApiApplicationsMutationError = void;

/**
 * @summary Create Application
 */
export const usePostApiApplications = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiApplications>>,
      TError,
      { data: PostApiApplicationsBody },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof postApiApplications>>,
  TError,
  { data: PostApiApplicationsBody },
  TContext
> => {
  const mutationOptions = getPostApiApplicationsMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * @summary Get Logo
 */
export const getApiApplicationsIdLogo = (
  id: MaybeRef<Uuid>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  id = unref(id);

  return customInstance<unknown>(
    { url: `/api/applications/${id}/logo`, method: "GET", signal },
    options,
  );
};

export const getGetApiApplicationsIdLogoQueryKey = (id: MaybeRef<Uuid>) => {
  return ["api", "applications", id, "logo"] as const;
};

export const getGetApiApplicationsIdLogoQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiApplicationsIdLogo>>,
  TError = unknown,
>(
  id: MaybeRef<Uuid>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiApplicationsIdLogo>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetApiApplicationsIdLogoQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiApplicationsIdLogo>>
  > = ({ signal }) => getApiApplicationsIdLogo(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(id)),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiApplicationsIdLogo>>,
    TError,
    TData
  >;
};

export type GetApiApplicationsIdLogoQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiApplicationsIdLogo>>
>;
export type GetApiApplicationsIdLogoQueryError = unknown;

/**
 * @summary Get Logo
 */

export function useGetApiApplicationsIdLogo<
  TData = Awaited<ReturnType<typeof getApiApplicationsIdLogo>>,
  TError = unknown,
>(
  id: MaybeRef<Uuid>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiApplicationsIdLogo>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiApplicationsIdLogoQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

/**
 * @summary Get Current User
 */
export const getApiMe = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<MeDto>(
    { url: `/api/me`, method: "GET", signal },
    options,
  );
};

export const getGetApiMeQueryKey = () => {
  return ["api", "me"] as const;
};

export const getGetApiMeQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiMe>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getApiMe>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetApiMeQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiMe>>> = ({
    signal,
  }) => getApiMe(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiMe>>,
    TError,
    TData
  >;
};

export type GetApiMeQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiMe>>
>;
export type GetApiMeQueryError = unknown;

/**
 * @summary Get Current User
 */

export function useGetApiMe<
  TData = Awaited<ReturnType<typeof getApiMe>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiMe>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiMeQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

/**
 * @summary Handle Bazarr Notification
 */
export const postApiNotificationsBazarr = (
  bazarrWebhookPayload: MaybeRef<BazarrWebhookPayload>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  bazarrWebhookPayload = unref(bazarrWebhookPayload);

  return customInstance<unknown>(
    {
      url: `/api/notifications/bazarr`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: bazarrWebhookPayload,
      signal,
    },
    options,
  );
};

export const getPostApiNotificationsBazarrMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiNotificationsBazarr>>,
    TError,
    { data: BazarrWebhookPayload },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiNotificationsBazarr>>,
  TError,
  { data: BazarrWebhookPayload },
  TContext
> => {
  const mutationKey = ["postApiNotificationsBazarr"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiNotificationsBazarr>>,
    { data: BazarrWebhookPayload }
  > = (props) => {
    const { data } = props ?? {};

    return postApiNotificationsBazarr(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiNotificationsBazarrMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiNotificationsBazarr>>
>;
export type PostApiNotificationsBazarrMutationBody = BazarrWebhookPayload;
export type PostApiNotificationsBazarrMutationError = void;

/**
 * @summary Handle Bazarr Notification
 */
export const usePostApiNotificationsBazarr = <
  TError = void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiNotificationsBazarr>>,
      TError,
      { data: BazarrWebhookPayload },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof postApiNotificationsBazarr>>,
  TError,
  { data: BazarrWebhookPayload },
  TContext
> => {
  const mutationOptions = getPostApiNotificationsBazarrMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * @summary Handle Lidarr Notification
 */
export const postApiNotificationsLidarr = (
  lidarrWebhookPayload: MaybeRef<LidarrWebhookPayload>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  lidarrWebhookPayload = unref(lidarrWebhookPayload);

  return customInstance<unknown>(
    {
      url: `/api/notifications/lidarr`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: lidarrWebhookPayload,
      signal,
    },
    options,
  );
};

export const getPostApiNotificationsLidarrMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiNotificationsLidarr>>,
    TError,
    { data: LidarrWebhookPayload },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiNotificationsLidarr>>,
  TError,
  { data: LidarrWebhookPayload },
  TContext
> => {
  const mutationKey = ["postApiNotificationsLidarr"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiNotificationsLidarr>>,
    { data: LidarrWebhookPayload }
  > = (props) => {
    const { data } = props ?? {};

    return postApiNotificationsLidarr(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiNotificationsLidarrMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiNotificationsLidarr>>
>;
export type PostApiNotificationsLidarrMutationBody = LidarrWebhookPayload;
export type PostApiNotificationsLidarrMutationError = void;

/**
 * @summary Handle Lidarr Notification
 */
export const usePostApiNotificationsLidarr = <
  TError = void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiNotificationsLidarr>>,
      TError,
      { data: LidarrWebhookPayload },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof postApiNotificationsLidarr>>,
  TError,
  { data: LidarrWebhookPayload },
  TContext
> => {
  const mutationOptions = getPostApiNotificationsLidarrMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * @summary Handle Radarr Notification
 */
export const postApiNotificationsRadarr = (
  radarrWebhookPayload: MaybeRef<RadarrWebhookPayload>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  radarrWebhookPayload = unref(radarrWebhookPayload);

  return customInstance<unknown>(
    {
      url: `/api/notifications/radarr`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: radarrWebhookPayload,
      signal,
    },
    options,
  );
};

export const getPostApiNotificationsRadarrMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiNotificationsRadarr>>,
    TError,
    { data: RadarrWebhookPayload },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiNotificationsRadarr>>,
  TError,
  { data: RadarrWebhookPayload },
  TContext
> => {
  const mutationKey = ["postApiNotificationsRadarr"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiNotificationsRadarr>>,
    { data: RadarrWebhookPayload }
  > = (props) => {
    const { data } = props ?? {};

    return postApiNotificationsRadarr(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiNotificationsRadarrMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiNotificationsRadarr>>
>;
export type PostApiNotificationsRadarrMutationBody = RadarrWebhookPayload;
export type PostApiNotificationsRadarrMutationError = void;

/**
 * @summary Handle Radarr Notification
 */
export const usePostApiNotificationsRadarr = <
  TError = void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiNotificationsRadarr>>,
      TError,
      { data: RadarrWebhookPayload },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof postApiNotificationsRadarr>>,
  TError,
  { data: RadarrWebhookPayload },
  TContext
> => {
  const mutationOptions = getPostApiNotificationsRadarrMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * @summary Handle Seerr Notification
 */
export const postApiNotificationsSeerr = (
  seerrWebhookPayload: MaybeRef<SeerrWebhookPayload>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  seerrWebhookPayload = unref(seerrWebhookPayload);

  return customInstance<unknown>(
    {
      url: `/api/notifications/seerr`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: seerrWebhookPayload,
      signal,
    },
    options,
  );
};

export const getPostApiNotificationsSeerrMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiNotificationsSeerr>>,
    TError,
    { data: SeerrWebhookPayload },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiNotificationsSeerr>>,
  TError,
  { data: SeerrWebhookPayload },
  TContext
> => {
  const mutationKey = ["postApiNotificationsSeerr"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiNotificationsSeerr>>,
    { data: SeerrWebhookPayload }
  > = (props) => {
    const { data } = props ?? {};

    return postApiNotificationsSeerr(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiNotificationsSeerrMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiNotificationsSeerr>>
>;
export type PostApiNotificationsSeerrMutationBody = SeerrWebhookPayload;
export type PostApiNotificationsSeerrMutationError = void;

/**
 * @summary Handle Seerr Notification
 */
export const usePostApiNotificationsSeerr = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiNotificationsSeerr>>,
      TError,
      { data: SeerrWebhookPayload },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof postApiNotificationsSeerr>>,
  TError,
  { data: SeerrWebhookPayload },
  TContext
> => {
  const mutationOptions = getPostApiNotificationsSeerrMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * @summary Send Weekly Report
 */
export const postApiNotificationsSendWeeklyReport = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<unknown>(
    { url: `/api/notifications/send-weekly-report`, method: "POST", signal },
    options,
  );
};

export const getPostApiNotificationsSendWeeklyReportMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiNotificationsSendWeeklyReport>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiNotificationsSendWeeklyReport>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["postApiNotificationsSendWeeklyReport"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiNotificationsSendWeeklyReport>>,
    void
  > = () => {
    return postApiNotificationsSendWeeklyReport(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiNotificationsSendWeeklyReportMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiNotificationsSendWeeklyReport>>
>;

export type PostApiNotificationsSendWeeklyReportMutationError = unknown;

/**
 * @summary Send Weekly Report
 */
export const usePostApiNotificationsSendWeeklyReport = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiNotificationsSendWeeklyReport>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof postApiNotificationsSendWeeklyReport>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions =
    getPostApiNotificationsSendWeeklyReportMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * @summary Handle Sonarr Notification
 */
export const postApiNotificationsSonarr = (
  sonarrWebhookPayload: MaybeRef<SonarrWebhookPayload>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  sonarrWebhookPayload = unref(sonarrWebhookPayload);

  return customInstance<unknown>(
    {
      url: `/api/notifications/sonarr`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: sonarrWebhookPayload,
      signal,
    },
    options,
  );
};

export const getPostApiNotificationsSonarrMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiNotificationsSonarr>>,
    TError,
    { data: SonarrWebhookPayload },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiNotificationsSonarr>>,
  TError,
  { data: SonarrWebhookPayload },
  TContext
> => {
  const mutationKey = ["postApiNotificationsSonarr"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiNotificationsSonarr>>,
    { data: SonarrWebhookPayload }
  > = (props) => {
    const { data } = props ?? {};

    return postApiNotificationsSonarr(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiNotificationsSonarrMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiNotificationsSonarr>>
>;
export type PostApiNotificationsSonarrMutationBody = SonarrWebhookPayload;
export type PostApiNotificationsSonarrMutationError = void;

/**
 * @summary Handle Sonarr Notification
 */
export const usePostApiNotificationsSonarr = <
  TError = void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiNotificationsSonarr>>,
      TError,
      { data: SonarrWebhookPayload },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof postApiNotificationsSonarr>>,
  TError,
  { data: SonarrWebhookPayload },
  TContext
> => {
  const mutationOptions = getPostApiNotificationsSonarrMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * @summary Get Stats
 */
export const getApiStats = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<LibraryStats>(
    { url: `/api/stats`, method: "GET", signal },
    options,
  );
};

export const getGetApiStatsQueryKey = () => {
  return ["api", "stats"] as const;
};

export const getGetApiStatsQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiStats>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getApiStats>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetApiStatsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiStats>>> = ({
    signal,
  }) => getApiStats(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiStats>>,
    TError,
    TData
  >;
};

export type GetApiStatsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiStats>>
>;
export type GetApiStatsQueryError = unknown;

/**
 * @summary Get Stats
 */

export function useGetApiStats<
  TData = Awaited<ReturnType<typeof getApiStats>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiStats>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiStatsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

/**
 * @summary Get Timeline
 */
export const getApiTimeline = (
  params: MaybeRef<GetApiTimelineParams>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  params = unref(params);

  return customInstance<TimelinePageDto>(
    { url: `/api/timeline`, method: "GET", params: unref(params), signal },
    options,
  );
};

export const getGetApiTimelineQueryKey = (
  params: MaybeRef<GetApiTimelineParams>,
) => {
  return ["api", "timeline", ...(params ? [params] : [])] as const;
};

export const getGetApiTimelineQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiTimeline>>,
  TError = unknown,
>(
  params: MaybeRef<GetApiTimelineParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiTimeline>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetApiTimelineQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiTimeline>>> = ({
    signal,
  }) => getApiTimeline(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiTimeline>>,
    TError,
    TData
  >;
};

export type GetApiTimelineQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiTimeline>>
>;
export type GetApiTimelineQueryError = unknown;

/**
 * @summary Get Timeline
 */

export function useGetApiTimeline<
  TData = Awaited<ReturnType<typeof getApiTimeline>>,
  TError = unknown,
>(
  params: MaybeRef<GetApiTimelineParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiTimeline>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiTimelineQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}
