/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */
import { useMutation, useQuery } from "@tanstack/vue-query";
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType,
} from "@tanstack/vue-query";

import { computed, unref } from "vue";
import type { MaybeRef } from "vue";

import type {
  ApplicationDto,
  BazarrWebhookPayload,
  CorrectorMovieDto,
  CorrectorReleaseDto,
  CorrectorWorkflowDto,
  CreateWorkflowRequest,
  GetApiCorrectorMoviesParams,
  GetApiTimelineParams,
  GrabReleaseRequest,
  JobStatusDto,
  LibraryStats,
  LidarrWebhookPayload,
  MeDto,
  PostApiApplicationsBody,
  PutApiApplicationsIdBody,
  RadarrWebhookPayload,
  SeerrWebhookPayload,
  SelectMovieRequest,
  SelectProblemRequest,
  SonarrWebhookPayload,
  TimelinePageDto,
  Uuid,
} from "../model";

import { customInstance } from "../axios-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary List Jobs
 */
export const getApiAdminJobs = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<JobStatusDto[]>(
    { url: `/api/admin/jobs`, method: "GET", signal },
    options,
  );
};

export const getGetApiAdminJobsQueryKey = () => {
  return ["api", "admin", "jobs"] as const;
};

export const getGetApiAdminJobsQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiAdminJobs>>,
  TError = void,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getApiAdminJobs>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetApiAdminJobsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAdminJobs>>> = ({
    signal,
  }) => getApiAdminJobs(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiAdminJobs>>,
    TError,
    TData
  >;
};

export type GetApiAdminJobsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiAdminJobs>>
>;
export type GetApiAdminJobsQueryError = void;

/**
 * @summary List Jobs
 */

export function useGetApiAdminJobs<
  TData = Awaited<ReturnType<typeof getApiAdminJobs>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiAdminJobs>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiAdminJobsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

/**
 * @summary Pause Job
 */
export const postApiAdminJobsIdentityPause = (
  identity: MaybeRef<string>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  identity = unref(identity);

  return customInstance<unknown>(
    { url: `/api/admin/jobs/${identity}/pause`, method: "POST", signal },
    options,
  );
};

export const getPostApiAdminJobsIdentityPauseMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiAdminJobsIdentityPause>>,
    TError,
    { identity: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiAdminJobsIdentityPause>>,
  TError,
  { identity: string },
  TContext
> => {
  const mutationKey = ["postApiAdminJobsIdentityPause"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiAdminJobsIdentityPause>>,
    { identity: string }
  > = (props) => {
    const { identity } = props ?? {};

    return postApiAdminJobsIdentityPause(identity, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiAdminJobsIdentityPauseMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiAdminJobsIdentityPause>>
>;

export type PostApiAdminJobsIdentityPauseMutationError = void;

/**
 * @summary Pause Job
 */
export const usePostApiAdminJobsIdentityPause = <
  TError = void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiAdminJobsIdentityPause>>,
      TError,
      { identity: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof postApiAdminJobsIdentityPause>>,
  TError,
  { identity: string },
  TContext
> => {
  const mutationOptions =
    getPostApiAdminJobsIdentityPauseMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * @summary Resume Job
 */
export const postApiAdminJobsIdentityResume = (
  identity: MaybeRef<string>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  identity = unref(identity);

  return customInstance<unknown>(
    { url: `/api/admin/jobs/${identity}/resume`, method: "POST", signal },
    options,
  );
};

export const getPostApiAdminJobsIdentityResumeMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiAdminJobsIdentityResume>>,
    TError,
    { identity: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiAdminJobsIdentityResume>>,
  TError,
  { identity: string },
  TContext
> => {
  const mutationKey = ["postApiAdminJobsIdentityResume"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiAdminJobsIdentityResume>>,
    { identity: string }
  > = (props) => {
    const { identity } = props ?? {};

    return postApiAdminJobsIdentityResume(identity, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiAdminJobsIdentityResumeMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiAdminJobsIdentityResume>>
>;

export type PostApiAdminJobsIdentityResumeMutationError = void;

/**
 * @summary Resume Job
 */
export const usePostApiAdminJobsIdentityResume = <
  TError = void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiAdminJobsIdentityResume>>,
      TError,
      { identity: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof postApiAdminJobsIdentityResume>>,
  TError,
  { identity: string },
  TContext
> => {
  const mutationOptions =
    getPostApiAdminJobsIdentityResumeMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * @summary Run Job
 */
export const postApiAdminJobsIdentityRun = (
  identity: MaybeRef<string>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  identity = unref(identity);

  return customInstance<unknown>(
    { url: `/api/admin/jobs/${identity}/run`, method: "POST", signal },
    options,
  );
};

export const getPostApiAdminJobsIdentityRunMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiAdminJobsIdentityRun>>,
    TError,
    { identity: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiAdminJobsIdentityRun>>,
  TError,
  { identity: string },
  TContext
> => {
  const mutationKey = ["postApiAdminJobsIdentityRun"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiAdminJobsIdentityRun>>,
    { identity: string }
  > = (props) => {
    const { identity } = props ?? {};

    return postApiAdminJobsIdentityRun(identity, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiAdminJobsIdentityRunMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiAdminJobsIdentityRun>>
>;

export type PostApiAdminJobsIdentityRunMutationError = void;

/**
 * @summary Run Job
 */
export const usePostApiAdminJobsIdentityRun = <
  TError = void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiAdminJobsIdentityRun>>,
      TError,
      { identity: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof postApiAdminJobsIdentityRun>>,
  TError,
  { identity: string },
  TContext
> => {
  const mutationOptions =
    getPostApiAdminJobsIdentityRunMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * @summary List Applications
 */
export const getApiApplications = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ApplicationDto[]>(
    { url: `/api/applications`, method: "GET", signal },
    options,
  );
};

export const getGetApiApplicationsQueryKey = () => {
  return ["api", "applications"] as const;
};

export const getGetApiApplicationsQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiApplications>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getApiApplications>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetApiApplicationsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiApplications>>
  > = ({ signal }) => getApiApplications(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiApplications>>,
    TError,
    TData
  >;
};

export type GetApiApplicationsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiApplications>>
>;
export type GetApiApplicationsQueryError = unknown;

/**
 * @summary List Applications
 */

export function useGetApiApplications<
  TData = Awaited<ReturnType<typeof getApiApplications>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiApplications>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiApplicationsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

/**
 * @summary Create Application
 */
export const postApiApplications = (
  postApiApplicationsBody: MaybeRef<PostApiApplicationsBody>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  postApiApplicationsBody = unref(postApiApplicationsBody);
  const formData = new FormData();
  if (postApiApplicationsBody.name !== null) {
    formData.append("name", postApiApplicationsBody.name);
  }
  if (postApiApplicationsBody.category !== null) {
    formData.append("category", postApiApplicationsBody.category);
  }
  if (postApiApplicationsBody.description !== null) {
    formData.append("description", postApiApplicationsBody.description);
  }
  if (postApiApplicationsBody.url !== null) {
    formData.append("url", postApiApplicationsBody.url);
  }
  formData.append(
    "requiresVpn",
    postApiApplicationsBody.requiresVpn.toString(),
  );
  if (postApiApplicationsBody.managedBy !== null) {
    formData.append("managedBy", postApiApplicationsBody.managedBy);
  }
  if (postApiApplicationsBody.externalId !== null) {
    formData.append("externalId", postApiApplicationsBody.externalId);
  }
  if (postApiApplicationsBody.logo !== null) {
    formData.append("logo", postApiApplicationsBody.logo);
  }

  return customInstance<ApplicationDto>(
    {
      url: `/api/applications`,
      method: "POST",
      headers: { "Content-Type": "multipart/form-data" },
      data: formData,
      signal,
    },
    options,
  );
};

export const getPostApiApplicationsMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiApplications>>,
    TError,
    { data: PostApiApplicationsBody },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiApplications>>,
  TError,
  { data: PostApiApplicationsBody },
  TContext
> => {
  const mutationKey = ["postApiApplications"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiApplications>>,
    { data: PostApiApplicationsBody }
  > = (props) => {
    const { data } = props ?? {};

    return postApiApplications(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiApplicationsMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiApplications>>
>;
export type PostApiApplicationsMutationBody = PostApiApplicationsBody;
export type PostApiApplicationsMutationError = void;

/**
 * @summary Create Application
 */
export const usePostApiApplications = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiApplications>>,
      TError,
      { data: PostApiApplicationsBody },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof postApiApplications>>,
  TError,
  { data: PostApiApplicationsBody },
  TContext
> => {
  const mutationOptions = getPostApiApplicationsMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * @summary Update Application
 */
export const putApiApplicationsId = (
  id: MaybeRef<Uuid>,
  putApiApplicationsIdBody: MaybeRef<PutApiApplicationsIdBody>,
  options?: SecondParameter<typeof customInstance>,
) => {
  id = unref(id);
  putApiApplicationsIdBody = unref(putApiApplicationsIdBody);
  const formData = new FormData();
  if (putApiApplicationsIdBody.name !== null) {
    formData.append("name", putApiApplicationsIdBody.name);
  }
  if (putApiApplicationsIdBody.category !== null) {
    formData.append("category", putApiApplicationsIdBody.category);
  }
  if (putApiApplicationsIdBody.description !== null) {
    formData.append("description", putApiApplicationsIdBody.description);
  }
  if (putApiApplicationsIdBody.url !== null) {
    formData.append("url", putApiApplicationsIdBody.url);
  }
  formData.append(
    "requiresVpn",
    putApiApplicationsIdBody.requiresVpn.toString(),
  );
  if (putApiApplicationsIdBody.managedBy !== null) {
    formData.append("managedBy", putApiApplicationsIdBody.managedBy);
  }
  if (putApiApplicationsIdBody.externalId !== null) {
    formData.append("externalId", putApiApplicationsIdBody.externalId);
  }
  if (putApiApplicationsIdBody.logo !== null) {
    formData.append("logo", putApiApplicationsIdBody.logo);
  }

  return customInstance<ApplicationDto>(
    {
      url: `/api/applications/${id}`,
      method: "PUT",
      headers: { "Content-Type": "multipart/form-data" },
      data: formData,
    },
    options,
  );
};

export const getPutApiApplicationsIdMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putApiApplicationsId>>,
    TError,
    { id: Uuid; data: PutApiApplicationsIdBody },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof putApiApplicationsId>>,
  TError,
  { id: Uuid; data: PutApiApplicationsIdBody },
  TContext
> => {
  const mutationKey = ["putApiApplicationsId"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putApiApplicationsId>>,
    { id: Uuid; data: PutApiApplicationsIdBody }
  > = (props) => {
    const { id, data } = props ?? {};

    return putApiApplicationsId(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutApiApplicationsIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof putApiApplicationsId>>
>;
export type PutApiApplicationsIdMutationBody = PutApiApplicationsIdBody;
export type PutApiApplicationsIdMutationError = void;

/**
 * @summary Update Application
 */
export const usePutApiApplicationsId = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putApiApplicationsId>>,
      TError,
      { id: Uuid; data: PutApiApplicationsIdBody },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof putApiApplicationsId>>,
  TError,
  { id: Uuid; data: PutApiApplicationsIdBody },
  TContext
> => {
  const mutationOptions = getPutApiApplicationsIdMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * @summary Delete Application
 */
export const deleteApiApplicationsId = (
  id: MaybeRef<Uuid>,
  options?: SecondParameter<typeof customInstance>,
) => {
  id = unref(id);

  return customInstance<unknown>(
    { url: `/api/applications/${id}`, method: "DELETE" },
    options,
  );
};

export const getDeleteApiApplicationsIdMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteApiApplicationsId>>,
    TError,
    { id: Uuid },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteApiApplicationsId>>,
  TError,
  { id: Uuid },
  TContext
> => {
  const mutationKey = ["deleteApiApplicationsId"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteApiApplicationsId>>,
    { id: Uuid }
  > = (props) => {
    const { id } = props ?? {};

    return deleteApiApplicationsId(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteApiApplicationsIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteApiApplicationsId>>
>;

export type DeleteApiApplicationsIdMutationError = void;

/**
 * @summary Delete Application
 */
export const useDeleteApiApplicationsId = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteApiApplicationsId>>,
      TError,
      { id: Uuid },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof deleteApiApplicationsId>>,
  TError,
  { id: Uuid },
  TContext
> => {
  const mutationOptions = getDeleteApiApplicationsIdMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * @summary Get Logo
 */
export const getApiApplicationsIdLogo = (
  id: MaybeRef<Uuid>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  id = unref(id);

  return customInstance<unknown>(
    { url: `/api/applications/${id}/logo`, method: "GET", signal },
    options,
  );
};

export const getGetApiApplicationsIdLogoQueryKey = (id: MaybeRef<Uuid>) => {
  return ["api", "applications", id, "logo"] as const;
};

export const getGetApiApplicationsIdLogoQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiApplicationsIdLogo>>,
  TError = unknown,
>(
  id: MaybeRef<Uuid>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiApplicationsIdLogo>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetApiApplicationsIdLogoQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiApplicationsIdLogo>>
  > = ({ signal }) => getApiApplicationsIdLogo(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(id)),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiApplicationsIdLogo>>,
    TError,
    TData
  >;
};

export type GetApiApplicationsIdLogoQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiApplicationsIdLogo>>
>;
export type GetApiApplicationsIdLogoQueryError = unknown;

/**
 * @summary Get Logo
 */

export function useGetApiApplicationsIdLogo<
  TData = Awaited<ReturnType<typeof getApiApplicationsIdLogo>>,
  TError = unknown,
>(
  id: MaybeRef<Uuid>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiApplicationsIdLogo>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiApplicationsIdLogoQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

/**
 * @summary Search Movies
 */
export const getApiCorrectorMovies = (
  params: MaybeRef<GetApiCorrectorMoviesParams>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  params = unref(params);

  return customInstance<CorrectorMovieDto[]>(
    {
      url: `/api/corrector/movies`,
      method: "GET",
      params: unref(params),
      signal,
    },
    options,
  );
};

export const getGetApiCorrectorMoviesQueryKey = (
  params: MaybeRef<GetApiCorrectorMoviesParams>,
) => {
  return ["api", "corrector", "movies", ...(params ? [params] : [])] as const;
};

export const getGetApiCorrectorMoviesQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiCorrectorMovies>>,
  TError = unknown,
>(
  params: MaybeRef<GetApiCorrectorMoviesParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiCorrectorMovies>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetApiCorrectorMoviesQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiCorrectorMovies>>
  > = ({ signal }) => getApiCorrectorMovies(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiCorrectorMovies>>,
    TError,
    TData
  >;
};

export type GetApiCorrectorMoviesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiCorrectorMovies>>
>;
export type GetApiCorrectorMoviesQueryError = unknown;

/**
 * @summary Search Movies
 */

export function useGetApiCorrectorMovies<
  TData = Awaited<ReturnType<typeof getApiCorrectorMovies>>,
  TError = unknown,
>(
  params: MaybeRef<GetApiCorrectorMoviesParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiCorrectorMovies>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiCorrectorMoviesQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

/**
 * @summary List Workflows
 */
export const getApiCorrectorWorkflows = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<CorrectorWorkflowDto[]>(
    { url: `/api/corrector/workflows`, method: "GET", signal },
    options,
  );
};

export const getGetApiCorrectorWorkflowsQueryKey = () => {
  return ["api", "corrector", "workflows"] as const;
};

export const getGetApiCorrectorWorkflowsQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiCorrectorWorkflows>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getApiCorrectorWorkflows>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetApiCorrectorWorkflowsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiCorrectorWorkflows>>
  > = ({ signal }) => getApiCorrectorWorkflows(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiCorrectorWorkflows>>,
    TError,
    TData
  >;
};

export type GetApiCorrectorWorkflowsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiCorrectorWorkflows>>
>;
export type GetApiCorrectorWorkflowsQueryError = unknown;

/**
 * @summary List Workflows
 */

export function useGetApiCorrectorWorkflows<
  TData = Awaited<ReturnType<typeof getApiCorrectorWorkflows>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiCorrectorWorkflows>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiCorrectorWorkflowsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

/**
 * @summary Create Workflow
 */
export const postApiCorrectorWorkflows = (
  createWorkflowRequest: MaybeRef<CreateWorkflowRequest>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  createWorkflowRequest = unref(createWorkflowRequest);

  return customInstance<CorrectorWorkflowDto>(
    {
      url: `/api/corrector/workflows`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createWorkflowRequest,
      signal,
    },
    options,
  );
};

export const getPostApiCorrectorWorkflowsMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiCorrectorWorkflows>>,
    TError,
    { data: CreateWorkflowRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiCorrectorWorkflows>>,
  TError,
  { data: CreateWorkflowRequest },
  TContext
> => {
  const mutationKey = ["postApiCorrectorWorkflows"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiCorrectorWorkflows>>,
    { data: CreateWorkflowRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postApiCorrectorWorkflows(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiCorrectorWorkflowsMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiCorrectorWorkflows>>
>;
export type PostApiCorrectorWorkflowsMutationBody = CreateWorkflowRequest;
export type PostApiCorrectorWorkflowsMutationError = void;

/**
 * @summary Create Workflow
 */
export const usePostApiCorrectorWorkflows = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiCorrectorWorkflows>>,
      TError,
      { data: CreateWorkflowRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof postApiCorrectorWorkflows>>,
  TError,
  { data: CreateWorkflowRequest },
  TContext
> => {
  const mutationOptions = getPostApiCorrectorWorkflowsMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * @summary Get Workflow
 */
export const getApiCorrectorWorkflowsId = (
  id: MaybeRef<Uuid>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  id = unref(id);

  return customInstance<CorrectorWorkflowDto>(
    { url: `/api/corrector/workflows/${id}`, method: "GET", signal },
    options,
  );
};

export const getGetApiCorrectorWorkflowsIdQueryKey = (id: MaybeRef<Uuid>) => {
  return ["api", "corrector", "workflows", id] as const;
};

export const getGetApiCorrectorWorkflowsIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiCorrectorWorkflowsId>>,
  TError = unknown,
>(
  id: MaybeRef<Uuid>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiCorrectorWorkflowsId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetApiCorrectorWorkflowsIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiCorrectorWorkflowsId>>
  > = ({ signal }) => getApiCorrectorWorkflowsId(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(id)),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiCorrectorWorkflowsId>>,
    TError,
    TData
  >;
};

export type GetApiCorrectorWorkflowsIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiCorrectorWorkflowsId>>
>;
export type GetApiCorrectorWorkflowsIdQueryError = unknown;

/**
 * @summary Get Workflow
 */

export function useGetApiCorrectorWorkflowsId<
  TData = Awaited<ReturnType<typeof getApiCorrectorWorkflowsId>>,
  TError = unknown,
>(
  id: MaybeRef<Uuid>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiCorrectorWorkflowsId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiCorrectorWorkflowsIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

/**
 * @summary Abandon Workflow
 */
export const postApiCorrectorWorkflowsIdAbandon = (
  id: MaybeRef<Uuid>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  id = unref(id);

  return customInstance<CorrectorWorkflowDto>(
    { url: `/api/corrector/workflows/${id}/abandon`, method: "POST", signal },
    options,
  );
};

export const getPostApiCorrectorWorkflowsIdAbandonMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiCorrectorWorkflowsIdAbandon>>,
    TError,
    { id: Uuid },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiCorrectorWorkflowsIdAbandon>>,
  TError,
  { id: Uuid },
  TContext
> => {
  const mutationKey = ["postApiCorrectorWorkflowsIdAbandon"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiCorrectorWorkflowsIdAbandon>>,
    { id: Uuid }
  > = (props) => {
    const { id } = props ?? {};

    return postApiCorrectorWorkflowsIdAbandon(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiCorrectorWorkflowsIdAbandonMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiCorrectorWorkflowsIdAbandon>>
>;

export type PostApiCorrectorWorkflowsIdAbandonMutationError = unknown;

/**
 * @summary Abandon Workflow
 */
export const usePostApiCorrectorWorkflowsIdAbandon = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiCorrectorWorkflowsIdAbandon>>,
      TError,
      { id: Uuid },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof postApiCorrectorWorkflowsIdAbandon>>,
  TError,
  { id: Uuid },
  TContext
> => {
  const mutationOptions =
    getPostApiCorrectorWorkflowsIdAbandonMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * @summary Grab Release
 */
export const postApiCorrectorWorkflowsIdGrab = (
  id: MaybeRef<Uuid>,
  grabReleaseRequest: MaybeRef<GrabReleaseRequest>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  id = unref(id);
  grabReleaseRequest = unref(grabReleaseRequest);

  return customInstance<CorrectorWorkflowDto>(
    {
      url: `/api/corrector/workflows/${id}/grab`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: grabReleaseRequest,
      signal,
    },
    options,
  );
};

export const getPostApiCorrectorWorkflowsIdGrabMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiCorrectorWorkflowsIdGrab>>,
    TError,
    { id: Uuid; data: GrabReleaseRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiCorrectorWorkflowsIdGrab>>,
  TError,
  { id: Uuid; data: GrabReleaseRequest },
  TContext
> => {
  const mutationKey = ["postApiCorrectorWorkflowsIdGrab"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiCorrectorWorkflowsIdGrab>>,
    { id: Uuid; data: GrabReleaseRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return postApiCorrectorWorkflowsIdGrab(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiCorrectorWorkflowsIdGrabMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiCorrectorWorkflowsIdGrab>>
>;
export type PostApiCorrectorWorkflowsIdGrabMutationBody = GrabReleaseRequest;
export type PostApiCorrectorWorkflowsIdGrabMutationError = void;

/**
 * @summary Grab Release
 */
export const usePostApiCorrectorWorkflowsIdGrab = <
  TError = void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiCorrectorWorkflowsIdGrab>>,
      TError,
      { id: Uuid; data: GrabReleaseRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof postApiCorrectorWorkflowsIdGrab>>,
  TError,
  { id: Uuid; data: GrabReleaseRequest },
  TContext
> => {
  const mutationOptions =
    getPostApiCorrectorWorkflowsIdGrabMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * @summary Select Movie
 */
export const postApiCorrectorWorkflowsIdMovie = (
  id: MaybeRef<Uuid>,
  selectMovieRequest: MaybeRef<SelectMovieRequest>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  id = unref(id);
  selectMovieRequest = unref(selectMovieRequest);

  return customInstance<CorrectorWorkflowDto>(
    {
      url: `/api/corrector/workflows/${id}/movie`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: selectMovieRequest,
      signal,
    },
    options,
  );
};

export const getPostApiCorrectorWorkflowsIdMovieMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiCorrectorWorkflowsIdMovie>>,
    TError,
    { id: Uuid; data: SelectMovieRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiCorrectorWorkflowsIdMovie>>,
  TError,
  { id: Uuid; data: SelectMovieRequest },
  TContext
> => {
  const mutationKey = ["postApiCorrectorWorkflowsIdMovie"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiCorrectorWorkflowsIdMovie>>,
    { id: Uuid; data: SelectMovieRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return postApiCorrectorWorkflowsIdMovie(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiCorrectorWorkflowsIdMovieMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiCorrectorWorkflowsIdMovie>>
>;
export type PostApiCorrectorWorkflowsIdMovieMutationBody = SelectMovieRequest;
export type PostApiCorrectorWorkflowsIdMovieMutationError = void;

/**
 * @summary Select Movie
 */
export const usePostApiCorrectorWorkflowsIdMovie = <
  TError = void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiCorrectorWorkflowsIdMovie>>,
      TError,
      { id: Uuid; data: SelectMovieRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof postApiCorrectorWorkflowsIdMovie>>,
  TError,
  { id: Uuid; data: SelectMovieRequest },
  TContext
> => {
  const mutationOptions =
    getPostApiCorrectorWorkflowsIdMovieMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * @summary Select Problem
 */
export const postApiCorrectorWorkflowsIdProblem = (
  id: MaybeRef<Uuid>,
  selectProblemRequest: MaybeRef<SelectProblemRequest>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  id = unref(id);
  selectProblemRequest = unref(selectProblemRequest);

  return customInstance<CorrectorWorkflowDto>(
    {
      url: `/api/corrector/workflows/${id}/problem`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: selectProblemRequest,
      signal,
    },
    options,
  );
};

export const getPostApiCorrectorWorkflowsIdProblemMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiCorrectorWorkflowsIdProblem>>,
    TError,
    { id: Uuid; data: SelectProblemRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiCorrectorWorkflowsIdProblem>>,
  TError,
  { id: Uuid; data: SelectProblemRequest },
  TContext
> => {
  const mutationKey = ["postApiCorrectorWorkflowsIdProblem"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiCorrectorWorkflowsIdProblem>>,
    { id: Uuid; data: SelectProblemRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return postApiCorrectorWorkflowsIdProblem(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiCorrectorWorkflowsIdProblemMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiCorrectorWorkflowsIdProblem>>
>;
export type PostApiCorrectorWorkflowsIdProblemMutationBody =
  SelectProblemRequest;
export type PostApiCorrectorWorkflowsIdProblemMutationError = void;

/**
 * @summary Select Problem
 */
export const usePostApiCorrectorWorkflowsIdProblem = <
  TError = void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiCorrectorWorkflowsIdProblem>>,
      TError,
      { id: Uuid; data: SelectProblemRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof postApiCorrectorWorkflowsIdProblem>>,
  TError,
  { id: Uuid; data: SelectProblemRequest },
  TContext
> => {
  const mutationOptions =
    getPostApiCorrectorWorkflowsIdProblemMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * @summary List Releases
 */
export const getApiCorrectorWorkflowsIdReleases = (
  id: MaybeRef<Uuid>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  id = unref(id);

  return customInstance<CorrectorReleaseDto[]>(
    { url: `/api/corrector/workflows/${id}/releases`, method: "GET", signal },
    options,
  );
};

export const getGetApiCorrectorWorkflowsIdReleasesQueryKey = (
  id: MaybeRef<Uuid>,
) => {
  return ["api", "corrector", "workflows", id, "releases"] as const;
};

export const getGetApiCorrectorWorkflowsIdReleasesQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiCorrectorWorkflowsIdReleases>>,
  TError = unknown,
>(
  id: MaybeRef<Uuid>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiCorrectorWorkflowsIdReleases>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetApiCorrectorWorkflowsIdReleasesQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiCorrectorWorkflowsIdReleases>>
  > = ({ signal }) =>
    getApiCorrectorWorkflowsIdReleases(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(id)),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiCorrectorWorkflowsIdReleases>>,
    TError,
    TData
  >;
};

export type GetApiCorrectorWorkflowsIdReleasesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiCorrectorWorkflowsIdReleases>>
>;
export type GetApiCorrectorWorkflowsIdReleasesQueryError = unknown;

/**
 * @summary List Releases
 */

export function useGetApiCorrectorWorkflowsIdReleases<
  TData = Awaited<ReturnType<typeof getApiCorrectorWorkflowsIdReleases>>,
  TError = unknown,
>(
  id: MaybeRef<Uuid>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiCorrectorWorkflowsIdReleases>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiCorrectorWorkflowsIdReleasesQueryOptions(
    id,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

/**
 * @summary Get Current User
 */
export const getApiMe = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<MeDto>(
    { url: `/api/me`, method: "GET", signal },
    options,
  );
};

export const getGetApiMeQueryKey = () => {
  return ["api", "me"] as const;
};

export const getGetApiMeQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiMe>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getApiMe>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetApiMeQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiMe>>> = ({
    signal,
  }) => getApiMe(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiMe>>,
    TError,
    TData
  >;
};

export type GetApiMeQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiMe>>
>;
export type GetApiMeQueryError = unknown;

/**
 * @summary Get Current User
 */

export function useGetApiMe<
  TData = Awaited<ReturnType<typeof getApiMe>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiMe>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiMeQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

/**
 * @summary Handle Bazarr Notification
 */
export const postApiNotificationsBazarr = (
  bazarrWebhookPayload: MaybeRef<BazarrWebhookPayload>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  bazarrWebhookPayload = unref(bazarrWebhookPayload);

  return customInstance<unknown>(
    {
      url: `/api/notifications/bazarr`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: bazarrWebhookPayload,
      signal,
    },
    options,
  );
};

export const getPostApiNotificationsBazarrMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiNotificationsBazarr>>,
    TError,
    { data: BazarrWebhookPayload },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiNotificationsBazarr>>,
  TError,
  { data: BazarrWebhookPayload },
  TContext
> => {
  const mutationKey = ["postApiNotificationsBazarr"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiNotificationsBazarr>>,
    { data: BazarrWebhookPayload }
  > = (props) => {
    const { data } = props ?? {};

    return postApiNotificationsBazarr(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiNotificationsBazarrMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiNotificationsBazarr>>
>;
export type PostApiNotificationsBazarrMutationBody = BazarrWebhookPayload;
export type PostApiNotificationsBazarrMutationError = void;

/**
 * @summary Handle Bazarr Notification
 */
export const usePostApiNotificationsBazarr = <
  TError = void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiNotificationsBazarr>>,
      TError,
      { data: BazarrWebhookPayload },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof postApiNotificationsBazarr>>,
  TError,
  { data: BazarrWebhookPayload },
  TContext
> => {
  const mutationOptions = getPostApiNotificationsBazarrMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * @summary Handle Lidarr Notification
 */
export const postApiNotificationsLidarr = (
  lidarrWebhookPayload: MaybeRef<LidarrWebhookPayload>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  lidarrWebhookPayload = unref(lidarrWebhookPayload);

  return customInstance<unknown>(
    {
      url: `/api/notifications/lidarr`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: lidarrWebhookPayload,
      signal,
    },
    options,
  );
};

export const getPostApiNotificationsLidarrMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiNotificationsLidarr>>,
    TError,
    { data: LidarrWebhookPayload },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiNotificationsLidarr>>,
  TError,
  { data: LidarrWebhookPayload },
  TContext
> => {
  const mutationKey = ["postApiNotificationsLidarr"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiNotificationsLidarr>>,
    { data: LidarrWebhookPayload }
  > = (props) => {
    const { data } = props ?? {};

    return postApiNotificationsLidarr(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiNotificationsLidarrMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiNotificationsLidarr>>
>;
export type PostApiNotificationsLidarrMutationBody = LidarrWebhookPayload;
export type PostApiNotificationsLidarrMutationError = void;

/**
 * @summary Handle Lidarr Notification
 */
export const usePostApiNotificationsLidarr = <
  TError = void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiNotificationsLidarr>>,
      TError,
      { data: LidarrWebhookPayload },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof postApiNotificationsLidarr>>,
  TError,
  { data: LidarrWebhookPayload },
  TContext
> => {
  const mutationOptions = getPostApiNotificationsLidarrMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * @summary Handle Radarr Notification
 */
export const postApiNotificationsRadarr = (
  radarrWebhookPayload: MaybeRef<RadarrWebhookPayload>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  radarrWebhookPayload = unref(radarrWebhookPayload);

  return customInstance<unknown>(
    {
      url: `/api/notifications/radarr`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: radarrWebhookPayload,
      signal,
    },
    options,
  );
};

export const getPostApiNotificationsRadarrMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiNotificationsRadarr>>,
    TError,
    { data: RadarrWebhookPayload },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiNotificationsRadarr>>,
  TError,
  { data: RadarrWebhookPayload },
  TContext
> => {
  const mutationKey = ["postApiNotificationsRadarr"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiNotificationsRadarr>>,
    { data: RadarrWebhookPayload }
  > = (props) => {
    const { data } = props ?? {};

    return postApiNotificationsRadarr(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiNotificationsRadarrMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiNotificationsRadarr>>
>;
export type PostApiNotificationsRadarrMutationBody = RadarrWebhookPayload;
export type PostApiNotificationsRadarrMutationError = void;

/**
 * @summary Handle Radarr Notification
 */
export const usePostApiNotificationsRadarr = <
  TError = void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiNotificationsRadarr>>,
      TError,
      { data: RadarrWebhookPayload },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof postApiNotificationsRadarr>>,
  TError,
  { data: RadarrWebhookPayload },
  TContext
> => {
  const mutationOptions = getPostApiNotificationsRadarrMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * @summary Handle Seerr Notification
 */
export const postApiNotificationsSeerr = (
  seerrWebhookPayload: MaybeRef<SeerrWebhookPayload>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  seerrWebhookPayload = unref(seerrWebhookPayload);

  return customInstance<unknown>(
    {
      url: `/api/notifications/seerr`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: seerrWebhookPayload,
      signal,
    },
    options,
  );
};

export const getPostApiNotificationsSeerrMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiNotificationsSeerr>>,
    TError,
    { data: SeerrWebhookPayload },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiNotificationsSeerr>>,
  TError,
  { data: SeerrWebhookPayload },
  TContext
> => {
  const mutationKey = ["postApiNotificationsSeerr"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiNotificationsSeerr>>,
    { data: SeerrWebhookPayload }
  > = (props) => {
    const { data } = props ?? {};

    return postApiNotificationsSeerr(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiNotificationsSeerrMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiNotificationsSeerr>>
>;
export type PostApiNotificationsSeerrMutationBody = SeerrWebhookPayload;
export type PostApiNotificationsSeerrMutationError = void;

/**
 * @summary Handle Seerr Notification
 */
export const usePostApiNotificationsSeerr = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiNotificationsSeerr>>,
      TError,
      { data: SeerrWebhookPayload },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof postApiNotificationsSeerr>>,
  TError,
  { data: SeerrWebhookPayload },
  TContext
> => {
  const mutationOptions = getPostApiNotificationsSeerrMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * @summary Send Weekly Report
 */
export const postApiNotificationsSendWeeklyReport = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<unknown>(
    { url: `/api/notifications/send-weekly-report`, method: "POST", signal },
    options,
  );
};

export const getPostApiNotificationsSendWeeklyReportMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiNotificationsSendWeeklyReport>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiNotificationsSendWeeklyReport>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["postApiNotificationsSendWeeklyReport"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiNotificationsSendWeeklyReport>>,
    void
  > = () => {
    return postApiNotificationsSendWeeklyReport(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiNotificationsSendWeeklyReportMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiNotificationsSendWeeklyReport>>
>;

export type PostApiNotificationsSendWeeklyReportMutationError = unknown;

/**
 * @summary Send Weekly Report
 */
export const usePostApiNotificationsSendWeeklyReport = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiNotificationsSendWeeklyReport>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof postApiNotificationsSendWeeklyReport>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions =
    getPostApiNotificationsSendWeeklyReportMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * @summary Handle Sonarr Notification
 */
export const postApiNotificationsSonarr = (
  sonarrWebhookPayload: MaybeRef<SonarrWebhookPayload>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  sonarrWebhookPayload = unref(sonarrWebhookPayload);

  return customInstance<unknown>(
    {
      url: `/api/notifications/sonarr`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: sonarrWebhookPayload,
      signal,
    },
    options,
  );
};

export const getPostApiNotificationsSonarrMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiNotificationsSonarr>>,
    TError,
    { data: SonarrWebhookPayload },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiNotificationsSonarr>>,
  TError,
  { data: SonarrWebhookPayload },
  TContext
> => {
  const mutationKey = ["postApiNotificationsSonarr"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiNotificationsSonarr>>,
    { data: SonarrWebhookPayload }
  > = (props) => {
    const { data } = props ?? {};

    return postApiNotificationsSonarr(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiNotificationsSonarrMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiNotificationsSonarr>>
>;
export type PostApiNotificationsSonarrMutationBody = SonarrWebhookPayload;
export type PostApiNotificationsSonarrMutationError = void;

/**
 * @summary Handle Sonarr Notification
 */
export const usePostApiNotificationsSonarr = <
  TError = void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiNotificationsSonarr>>,
      TError,
      { data: SonarrWebhookPayload },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof postApiNotificationsSonarr>>,
  TError,
  { data: SonarrWebhookPayload },
  TContext
> => {
  const mutationOptions = getPostApiNotificationsSonarrMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * @summary Get Stats
 */
export const getApiStats = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<LibraryStats>(
    { url: `/api/stats`, method: "GET", signal },
    options,
  );
};

export const getGetApiStatsQueryKey = () => {
  return ["api", "stats"] as const;
};

export const getGetApiStatsQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiStats>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getApiStats>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetApiStatsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiStats>>> = ({
    signal,
  }) => getApiStats(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiStats>>,
    TError,
    TData
  >;
};

export type GetApiStatsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiStats>>
>;
export type GetApiStatsQueryError = unknown;

/**
 * @summary Get Stats
 */

export function useGetApiStats<
  TData = Awaited<ReturnType<typeof getApiStats>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiStats>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiStatsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

/**
 * @summary Get Timeline
 */
export const getApiTimeline = (
  params: MaybeRef<GetApiTimelineParams>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  params = unref(params);

  return customInstance<TimelinePageDto>(
    { url: `/api/timeline`, method: "GET", params: unref(params), signal },
    options,
  );
};

export const getGetApiTimelineQueryKey = (
  params: MaybeRef<GetApiTimelineParams>,
) => {
  return ["api", "timeline", ...(params ? [params] : [])] as const;
};

export const getGetApiTimelineQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiTimeline>>,
  TError = unknown,
>(
  params: MaybeRef<GetApiTimelineParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiTimeline>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetApiTimelineQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiTimeline>>> = ({
    signal,
  }) => getApiTimeline(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiTimeline>>,
    TError,
    TData
  >;
};

export type GetApiTimelineQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiTimeline>>
>;
export type GetApiTimelineQueryError = unknown;

/**
 * @summary Get Timeline
 */

export function useGetApiTimeline<
  TData = Awaited<ReturnType<typeof getApiTimeline>>,
  TError = unknown,
>(
  params: MaybeRef<GetApiTimelineParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiTimeline>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiTimelineQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}
