/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */

export type GetApiMediaInfoWhoWatchedParams = {
  /**
   * The term you want to find watched information for
   */
  searchTerm: string;
};
