/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */

export * from "./getApiMediaInfoTopWatchersParams";
export * from "./getApiMediaInfoWhoWatchedParams";
export * from "./jsonObject";
export * from "./jsonObjectItem";
export * from "./mostPopularMedia";
export * from "./mostViewedMedia";
export * from "./topWatched";
export * from "./topWatchedPeriod";
export * from "./unit";
export * from "./userStatistics";
export * from "./watcherInfo";
export * from "./whoWatchedInfos";
