/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */
import type { TopWatchedPeriod } from "./topWatchedPeriod";
import type { MostPopularMedia } from "./mostPopularMedia";
import type { MostViewedMedia } from "./mostViewedMedia";

export interface TopWatched {
  period: TopWatchedPeriod;
  mostPopularSeries: MostPopularMedia[];
  mostPopularMovies: MostPopularMedia[];
  mostViewedSeries: MostViewedMedia[];
  mostViewedMovies: MostViewedMedia[];
}
