/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */
import type { Uuid } from "./uuid";
import type { ApplicationDtoUpdatedAt } from "./applicationDtoUpdatedAt";

export interface ApplicationDto {
  id: Uuid;
  name: string;
  category: string;
  description: string;
  url: string;
  requiresVpn: boolean;
  hasLogo: boolean;
  updatedAt: ApplicationDtoUpdatedAt;
}
