/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */
import type { Uuid } from "./uuid";
import type { ApplicationDtoLogoSourceUrl } from "./applicationDtoLogoSourceUrl";
import type { ApplicationDtoManagedBy } from "./applicationDtoManagedBy";
import type { ApplicationDtoExternalId } from "./applicationDtoExternalId";
import type { ApplicationDtoUpdatedAt } from "./applicationDtoUpdatedAt";

export interface ApplicationDto {
  id: Uuid;
  name: string;
  category: string;
  description: string;
  url: string;
  requiresVpn: boolean;
  hasLogo: boolean;
  logoSourceUrl: ApplicationDtoLogoSourceUrl;
  managedBy: ApplicationDtoManagedBy;
  externalId: ApplicationDtoExternalId;
  updatedAt: ApplicationDtoUpdatedAt;
}
