/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */
import type { BazarrWebhookPayloadTitle } from "./bazarrWebhookPayloadTitle";
import type { BazarrWebhookPayloadMessage } from "./bazarrWebhookPayloadMessage";
import type { BazarrWebhookPayloadType } from "./bazarrWebhookPayloadType";

export interface BazarrWebhookPayload {
  title?: BazarrWebhookPayloadTitle;
  message?: BazarrWebhookPayloadMessage;
  type?: BazarrWebhookPayloadType;
}
