/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */
import type { CleanupOverviewDtoCampaign } from "./cleanupOverviewDtoCampaign";
import type { CleanupOverviewDtoDiskFreeBytes } from "./cleanupOverviewDtoDiskFreeBytes";

export interface CleanupOverviewDto {
  campaign: CleanupOverviewDtoCampaign;
  diskPath: string;
  diskFreeBytes: CleanupOverviewDtoDiskFreeBytes;
  thresholdBytes: number;
  targetFreeBytes: number;
}
