/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */
import type { Uuid } from "./uuid";
import type { CleanupCandidateDtoYear } from "./cleanupCandidateDtoYear";
import type { CleanupCandidateDtoPosterUrl } from "./cleanupCandidateDtoPosterUrl";
import type { CleanupCandidateDtoSeasonNumber } from "./cleanupCandidateDtoSeasonNumber";
import type { CleanupCandidateDtoRequester } from "./cleanupCandidateDtoRequester";
import type { ScoreBreakdown } from "./scoreBreakdown";
import type { CleanupCandidateDtoProtectedBy } from "./cleanupCandidateDtoProtectedBy";
import type { CleanupCandidateDtoProtectedVia } from "./cleanupCandidateDtoProtectedVia";
import type { CleanupCandidateDtoDeletedAt } from "./cleanupCandidateDtoDeletedAt";
import type { CleanupCandidateDtoFreedBytes } from "./cleanupCandidateDtoFreedBytes";
import type { CleanupCandidateDtoFailureReason } from "./cleanupCandidateDtoFailureReason";

export interface CleanupCandidateDto {
  id: Uuid;
  mediaKind: string;
  title: string;
  displayTitle: string;
  year: CleanupCandidateDtoYear;
  posterUrl: CleanupCandidateDtoPosterUrl;
  seasonNumber: CleanupCandidateDtoSeasonNumber;
  sizeBytes: number;
  requester: CleanupCandidateDtoRequester;
  status: string;
  score: number;
  scoreBreakdown: ScoreBreakdown;
  protectedBy: CleanupCandidateDtoProtectedBy;
  protectedVia: CleanupCandidateDtoProtectedVia;
  deletedAt: CleanupCandidateDtoDeletedAt;
  freedBytes: CleanupCandidateDtoFreedBytes;
  failureReason: CleanupCandidateDtoFailureReason;
}
