/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */
import type { CleanupConfigDtoDiskFreeBytes } from "./cleanupConfigDtoDiskFreeBytes";

export interface CleanupConfigDto {
  diskPath: string;
  thresholdBytes: number;
  targetFreeBytes: number;
  graceDays: number;
  minAgeDays: number;
  recentSeriesWatchDays: number;
  inProgressDays: number;
  maxCandidates: number;
  minScore: number;
  weightLastWatched: number;
  weightDownloadAge: number;
  weightSize: number;
  weightCompletion: number;
  weightRequesterActivity: number;
  knownDiskPaths: string[];
  diskFreeBytes: CleanupConfigDtoDiskFreeBytes;
}
