/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */
import type { ExecutionSummary } from "./executionSummary";

export type CleanupCampaignDetailsDtoExecutionSummary = ExecutionSummary | null;
