/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */
import type { Uuid } from "./uuid";
import type { CleanupProtectionDtoRadarrMovieId } from "./cleanupProtectionDtoRadarrMovieId";
import type { CleanupProtectionDtoSonarrSeriesId } from "./cleanupProtectionDtoSonarrSeriesId";
import type { CleanupProtectionDtoSeasonNumber } from "./cleanupProtectionDtoSeasonNumber";
import type { CleanupProtectionDtoYear } from "./cleanupProtectionDtoYear";
import type { CleanupProtectionDtoPosterUrl } from "./cleanupProtectionDtoPosterUrl";
import type { LocalDateTime } from "./localDateTime";

export interface CleanupProtectionDto {
  id: Uuid;
  mediaKind: string;
  radarrMovieId: CleanupProtectionDtoRadarrMovieId;
  sonarrSeriesId: CleanupProtectionDtoSonarrSeriesId;
  seasonNumber: CleanupProtectionDtoSeasonNumber;
  title: string;
  year: CleanupProtectionDtoYear;
  posterUrl: CleanupProtectionDtoPosterUrl;
  protectedBy: string;
  source: string;
  createdAt: LocalDateTime;
}
