/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */
import type { Uuid } from "./uuid";
import type { CleanupSuggestionDtoRadarrMovieId } from "./cleanupSuggestionDtoRadarrMovieId";
import type { CleanupSuggestionDtoSonarrSeriesId } from "./cleanupSuggestionDtoSonarrSeriesId";
import type { CleanupSuggestionDtoSeasonNumber } from "./cleanupSuggestionDtoSeasonNumber";
import type { CleanupSuggestionDtoYear } from "./cleanupSuggestionDtoYear";
import type { CleanupSuggestionDtoPosterUrl } from "./cleanupSuggestionDtoPosterUrl";
import type { OffsetDateTime } from "./offsetDateTime";
import type { CleanupSuggestionDtoVetoedBy } from "./cleanupSuggestionDtoVetoedBy";
import type { CleanupSuggestionDtoFreedBytes } from "./cleanupSuggestionDtoFreedBytes";
import type { CleanupSuggestionDtoFailureReason } from "./cleanupSuggestionDtoFailureReason";
import type { LocalDateTime } from "./localDateTime";

export interface CleanupSuggestionDto {
  id: Uuid;
  mediaKind: string;
  radarrMovieId: CleanupSuggestionDtoRadarrMovieId;
  sonarrSeriesId: CleanupSuggestionDtoSonarrSeriesId;
  seasonNumber: CleanupSuggestionDtoSeasonNumber;
  title: string;
  displayTitle: string;
  year: CleanupSuggestionDtoYear;
  posterUrl: CleanupSuggestionDtoPosterUrl;
  sizeBytes: number;
  suggestedBy: string;
  status: string;
  deleteAfter: OffsetDateTime;
  vetoedBy: CleanupSuggestionDtoVetoedBy;
  freedBytes: CleanupSuggestionDtoFreedBytes;
  failureReason: CleanupSuggestionDtoFailureReason;
  createdAt: LocalDateTime;
}
