/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */
import type { Uuid } from "./uuid";
import type { OffsetDateTime } from "./offsetDateTime";
import type { LocalDateTime } from "./localDateTime";
import type { CleanupCampaignDetailsDtoCompletedAt } from "./cleanupCampaignDetailsDtoCompletedAt";
import type { CleanupCampaignDetailsDtoExecutionSummary } from "./cleanupCampaignDetailsDtoExecutionSummary";
import type { CleanupCandidateDto } from "./cleanupCandidateDto";

export interface CleanupCampaignDetailsDto {
  id: Uuid;
  status: string;
  triggerType: string;
  diskPath: string;
  freeBytesAtStart: number;
  targetBytesToFree: number;
  freedBytes: number;
  graceEndsAt: OffsetDateTime;
  createdAt: LocalDateTime;
  completedAt: CleanupCampaignDetailsDtoCompletedAt;
  executionSummary: CleanupCampaignDetailsDtoExecutionSummary;
  candidates: CleanupCandidateDto[];
}
