/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */
import type { Uuid } from "./uuid";
import type { LocalDateTime } from "./localDateTime";
import type { OffsetDateTime } from "./offsetDateTime";
import type { CleanupCampaignSummaryDtoCompletedAt } from "./cleanupCampaignSummaryDtoCompletedAt";

export interface CleanupCampaignSummaryDto {
  id: Uuid;
  status: string;
  triggerType: string;
  createdAt: LocalDateTime;
  graceEndsAt: OffsetDateTime;
  completedAt: CleanupCampaignSummaryDtoCompletedAt;
  targetBytesToFree: number;
  freedBytes: number;
  candidateCount: number;
  deletedCount: number;
  protectedCount: number;
  skippedCount: number;
  failedCount: number;
}
