/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */
import type { CleanupMediaDtoRadarrMovieId } from "./cleanupMediaDtoRadarrMovieId";
import type { CleanupMediaDtoSonarrSeriesId } from "./cleanupMediaDtoSonarrSeriesId";
import type { CleanupMediaDtoYear } from "./cleanupMediaDtoYear";
import type { CleanupMediaDtoPosterUrl } from "./cleanupMediaDtoPosterUrl";

export interface CleanupMediaDto {
  mediaKind: string;
  radarrMovieId: CleanupMediaDtoRadarrMovieId;
  sonarrSeriesId: CleanupMediaDtoSonarrSeriesId;
  title: string;
  year: CleanupMediaDtoYear;
  posterUrl: CleanupMediaDtoPosterUrl;
  seasonNumbers: number[];
}
