/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */
import type { CorrectorReleaseDtoIndexer } from "./correctorReleaseDtoIndexer";
import type { CorrectorReleaseDtoQuality } from "./correctorReleaseDtoQuality";
import type { CorrectorReleaseDtoSize } from "./correctorReleaseDtoSize";
import type { CorrectorReleaseDtoAge } from "./correctorReleaseDtoAge";
import type { CorrectorReleaseDtoSeeders } from "./correctorReleaseDtoSeeders";
import type { CorrectorReleaseDtoLeechers } from "./correctorReleaseDtoLeechers";
import type { CorrectorReleaseDtoProtocol } from "./correctorReleaseDtoProtocol";

export interface CorrectorReleaseDto {
  guid: string;
  indexerId: number;
  indexer: CorrectorReleaseDtoIndexer;
  title: string;
  quality: CorrectorReleaseDtoQuality;
  size: CorrectorReleaseDtoSize;
  age: CorrectorReleaseDtoAge;
  seeders: CorrectorReleaseDtoSeeders;
  leechers: CorrectorReleaseDtoLeechers;
  protocol: CorrectorReleaseDtoProtocol;
  rejected: boolean;
  rejections: string[];
  isFrench: boolean;
}
