/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */
import type { CorrectorMovieDtoYear } from "./correctorMovieDtoYear";
import type { CorrectorMovieDtoPosterUrl } from "./correctorMovieDtoPosterUrl";

export interface CorrectorMovieDto {
  radarrMovieId: number;
  title: string;
  year: CorrectorMovieDtoYear;
  posterUrl: CorrectorMovieDtoPosterUrl;
}
