/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */
import type { Uuid } from "./uuid";
import type { CorrectorWorkflowDtoProblemType } from "./correctorWorkflowDtoProblemType";
import type { CorrectorWorkflowDtoMovie } from "./correctorWorkflowDtoMovie";
import type { CorrectorWorkflowDtoGrabbedRelease } from "./correctorWorkflowDtoGrabbedRelease";
import type { LocalDateTime } from "./localDateTime";
import type { CorrectorWorkflowDtoCompletedAt } from "./correctorWorkflowDtoCompletedAt";

export interface CorrectorWorkflowDto {
  id: Uuid;
  mediaType: string;
  status: string;
  currentStep: string;
  problemType: CorrectorWorkflowDtoProblemType;
  movie: CorrectorWorkflowDtoMovie;
  grabbedRelease: CorrectorWorkflowDtoGrabbedRelease;
  createdAt: LocalDateTime;
  updatedAt: LocalDateTime;
  completedAt: CorrectorWorkflowDtoCompletedAt;
}
