/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */
import type { CreateSuggestionRequestMediaKind } from "./createSuggestionRequestMediaKind";
import type { CreateSuggestionRequestRadarrMovieId } from "./createSuggestionRequestRadarrMovieId";
import type { CreateSuggestionRequestSonarrSeriesId } from "./createSuggestionRequestSonarrSeriesId";
import type { CreateSuggestionRequestSeasonNumber } from "./createSuggestionRequestSeasonNumber";

export interface CreateSuggestionRequest {
  mediaKind: CreateSuggestionRequestMediaKind;
  radarrMovieId: CreateSuggestionRequestRadarrMovieId;
  sonarrSeriesId: CreateSuggestionRequestSonarrSeriesId;
  seasonNumber: CreateSuggestionRequestSeasonNumber;
}
