/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */
import type { CreateProtectionRequestMediaKind } from "./createProtectionRequestMediaKind";
import type { CreateProtectionRequestRadarrMovieId } from "./createProtectionRequestRadarrMovieId";
import type { CreateProtectionRequestSonarrSeriesId } from "./createProtectionRequestSonarrSeriesId";
import type { CreateProtectionRequestSeasonNumber } from "./createProtectionRequestSeasonNumber";

export interface CreateProtectionRequest {
  mediaKind: CreateProtectionRequestMediaKind;
  radarrMovieId: CreateProtectionRequestRadarrMovieId;
  sonarrSeriesId: CreateProtectionRequestSonarrSeriesId;
  seasonNumber: CreateProtectionRequestSeasonNumber;
}
