/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */
import type { EnergyStatusDtoCurrentPowerWatts } from "./energyStatusDtoCurrentPowerWatts";
import type { EnergyStatusDtoEstimatedMonthlyKwh } from "./energyStatusDtoEstimatedMonthlyKwh";
import type { EnergyStatusDtoEstimatedMonthlyCostCents } from "./energyStatusDtoEstimatedMonthlyCostCents";

export interface EnergyStatusDto {
  currentPowerWatts: EnergyStatusDtoCurrentPowerWatts;
  estimatedMonthlyKwh: EnergyStatusDtoEstimatedMonthlyKwh;
  estimatedMonthlyCostCents: EnergyStatusDtoEstimatedMonthlyCostCents;
  kwhPriceConfigured: boolean;
}
