/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */

export type EntryType = (typeof EntryType)[keyof typeof EntryType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EntryType = {
  CONTRIBUTION: "CONTRIBUTION",
  EXPENSE: "EXPENSE",
} as const;
