/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */

export type EntrySource = (typeof EntrySource)[keyof typeof EntrySource];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EntrySource = {
  MANUAL: "MANUAL",
  RECURRING: "RECURRING",
  ENERGY: "ENERGY",
} as const;
