/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */
import type { ExecutionSummaryFinishedAt } from "./executionSummaryFinishedAt";
import type { ExecutionSummaryNote } from "./executionSummaryNote";

export interface ExecutionSummary {
  deletedCount?: number;
  protectedCount?: number;
  skippedCount?: number;
  failedCount?: number;
  freedBytes?: number;
  finishedAt?: ExecutionSummaryFinishedAt;
  note?: ExecutionSummaryNote;
}
