/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */
import type { FinanceSettingsDtoKwhPrice } from "./financeSettingsDtoKwhPrice";

export interface FinanceSettingsDto {
  kwhPrice: FinanceSettingsDtoKwhPrice;
}
