/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */
import type { Uuid } from "./uuid";
import type { EntryType } from "./entryType";
import type { EntrySource } from "./entrySource";
import type { FinanceEntryDtoVendor } from "./financeEntryDtoVendor";
import type { LocalDate } from "./localDate";
import type { FinanceEntryDtoMemberId } from "./financeEntryDtoMemberId";
import type { FinanceEntryDtoMemberDisplayName } from "./financeEntryDtoMemberDisplayName";
import type { FinanceEntryDtoPeriod } from "./financeEntryDtoPeriod";
import type { FinanceEntryDtoNotes } from "./financeEntryDtoNotes";

export interface FinanceEntryDto {
  id: Uuid;
  type: EntryType;
  source: EntrySource;
  label: string;
  vendor: FinanceEntryDtoVendor;
  amountCents: number;
  entryDate: LocalDate;
  memberId: FinanceEntryDtoMemberId;
  memberDisplayName: FinanceEntryDtoMemberDisplayName;
  period: FinanceEntryDtoPeriod;
  notes: FinanceEntryDtoNotes;
}
