/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */
import type { FinanceEntryRequestType } from "./financeEntryRequestType";
import type { FinanceEntryRequestLabel } from "./financeEntryRequestLabel";
import type { FinanceEntryRequestVendor } from "./financeEntryRequestVendor";
import type { FinanceEntryRequestAmountCents } from "./financeEntryRequestAmountCents";
import type { FinanceEntryRequestEntryDate } from "./financeEntryRequestEntryDate";
import type { FinanceEntryRequestMemberId } from "./financeEntryRequestMemberId";
import type { FinanceEntryRequestNotes } from "./financeEntryRequestNotes";

export interface FinanceEntryRequest {
  type: FinanceEntryRequestType;
  label: FinanceEntryRequestLabel;
  vendor: FinanceEntryRequestVendor;
  amountCents: FinanceEntryRequestAmountCents;
  entryDate: FinanceEntryRequestEntryDate;
  memberId: FinanceEntryRequestMemberId;
  notes: FinanceEntryRequestNotes;
}
