/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */
import type { EntryType } from "./entryType";

export type GetApiFinancesEntriesParams = {
  page: number | null;
  pageSize: number | null;
  type: EntryType | null;
  year: number | null;
};
