/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */
import type { SortDirection } from "./sortDirection";
import type { StatsPeriod } from "./statsPeriod";
import type { TopMediaSort } from "./topMediaSort";
import type { MediaKind } from "./mediaKind";

export type GetApiStatisticsTopMediaParams = {
  order: SortDirection | null;
  period: StatsPeriod | null;
  sort: TopMediaSort | null;
  type: MediaKind | null;
};
