/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */
import type { GrabbedReleaseGuid } from "./grabbedReleaseGuid";
import type { GrabbedReleaseIndexerId } from "./grabbedReleaseIndexerId";
import type { GrabbedReleaseIndexer } from "./grabbedReleaseIndexer";
import type { GrabbedReleaseTitle } from "./grabbedReleaseTitle";
import type { GrabbedReleaseQuality } from "./grabbedReleaseQuality";
import type { GrabbedReleaseSize } from "./grabbedReleaseSize";

export interface GrabbedRelease {
  guid?: GrabbedReleaseGuid;
  indexerId?: GrabbedReleaseIndexerId;
  indexer?: GrabbedReleaseIndexer;
  title?: GrabbedReleaseTitle;
  quality?: GrabbedReleaseQuality;
  size?: GrabbedReleaseSize;
}
