/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */
import type { GrabReleaseRequestGuid } from "./grabReleaseRequestGuid";
import type { GrabReleaseRequestIndexerId } from "./grabReleaseRequestIndexerId";
import type { GrabReleaseRequestTitle } from "./grabReleaseRequestTitle";
import type { GrabReleaseRequestIndexer } from "./grabReleaseRequestIndexer";
import type { GrabReleaseRequestQuality } from "./grabReleaseRequestQuality";
import type { GrabReleaseRequestSize } from "./grabReleaseRequestSize";

export interface GrabReleaseRequest {
  guid: GrabReleaseRequestGuid;
  indexerId: GrabReleaseRequestIndexerId;
  title: GrabReleaseRequestTitle;
  indexer: GrabReleaseRequestIndexer;
  quality: GrabReleaseRequestQuality;
  size: GrabReleaseRequestSize;
}
