/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */

export interface HourActivityDto {
  hour: number;
  plays: number;
  watchTimeSeconds: number;
}
