/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */
import type { LocalDateTime } from "./localDateTime";
import type { JobExecutionDtoDurationMs } from "./jobExecutionDtoDurationMs";
import type { JobExecutionDtoError } from "./jobExecutionDtoError";

export interface JobExecutionDto {
  runAt: LocalDateTime;
  status: string;
  durationMs: JobExecutionDtoDurationMs;
  error: JobExecutionDtoError;
  manual: boolean;
}
