/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */
import type { JobStatusDtoDisplayName } from "./jobStatusDtoDisplayName";
import type { JobStatusDtoSchedule } from "./jobStatusDtoSchedule";
import type { JobStatusDtoNextFireTime } from "./jobStatusDtoNextFireTime";
import type { JobStatusDtoLastExecution } from "./jobStatusDtoLastExecution";

export interface JobStatusDto {
  identity: string;
  displayName: JobStatusDtoDisplayName;
  schedule: JobStatusDtoSchedule;
  nextFireTime: JobStatusDtoNextFireTime;
  paused: boolean;
  runnable: boolean;
  lastExecution: JobStatusDtoLastExecution;
}
