/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */
import type { LidarrWebhookAlbumTitle } from "./lidarrWebhookAlbumTitle";
import type { LidarrWebhookAlbumReleaseDate } from "./lidarrWebhookAlbumReleaseDate";
import type { LidarrWebhookAlbumGenres } from "./lidarrWebhookAlbumGenres";
import type { LidarrWebhookAlbumImages } from "./lidarrWebhookAlbumImages";

export interface LidarrWebhookAlbum {
  title?: LidarrWebhookAlbumTitle;
  releaseDate?: LidarrWebhookAlbumReleaseDate;
  genres?: LidarrWebhookAlbumGenres;
  images?: LidarrWebhookAlbumImages;
}
