/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */
import type { LidarrWebhookPayloadEventType } from "./lidarrWebhookPayloadEventType";
import type { LidarrWebhookPayloadArtist } from "./lidarrWebhookPayloadArtist";
import type { LidarrWebhookPayloadAlbum } from "./lidarrWebhookPayloadAlbum";
import type { LidarrWebhookPayloadDownloadClient } from "./lidarrWebhookPayloadDownloadClient";

export interface LidarrWebhookPayload {
  eventType?: LidarrWebhookPayloadEventType;
  artist?: LidarrWebhookPayloadArtist;
  album?: LidarrWebhookPayloadAlbum;
  downloadClient?: LidarrWebhookPayloadDownloadClient;
}
