/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */

export type MediaKind = (typeof MediaKind)[keyof typeof MediaKind];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MediaKind = {
  MOVIE: "MOVIE",
  SERIES: "SERIES",
} as const;
