/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */
import type { Uuid } from "./uuid";
import type { MemberDtoEmail } from "./memberDtoEmail";

export interface MemberDto {
  id: Uuid;
  username: string;
  displayName: string;
  email: MemberDtoEmail;
  active: boolean;
  fromAuthentik: boolean;
}
