/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */
import type { MovieSnapshotTitle } from "./movieSnapshotTitle";
import type { MovieSnapshotYear } from "./movieSnapshotYear";
import type { MovieSnapshotPosterUrl } from "./movieSnapshotPosterUrl";
import type { MovieSnapshotOverview } from "./movieSnapshotOverview";
import type { MovieSnapshotCurrentQuality } from "./movieSnapshotCurrentQuality";

export interface MovieSnapshot {
  title?: MovieSnapshotTitle;
  year?: MovieSnapshotYear;
  posterUrl?: MovieSnapshotPosterUrl;
  overview?: MovieSnapshotOverview;
  currentQuality?: MovieSnapshotCurrentQuality;
  currentLanguages?: string[];
}
