/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */
import type { NowPlayingDtoSeriesName } from "./nowPlayingDtoSeriesName";
import type { NowPlayingDtoSeasonNumber } from "./nowPlayingDtoSeasonNumber";
import type { NowPlayingDtoEpisodeNumber } from "./nowPlayingDtoEpisodeNumber";
import type { NowPlayingDtoProgressPercent } from "./nowPlayingDtoProgressPercent";
import type { NowPlayingDtoClient } from "./nowPlayingDtoClient";
import type { LocalDateTime } from "./localDateTime";

export interface NowPlayingDto {
  userName: string;
  itemName: string;
  seriesName: NowPlayingDtoSeriesName;
  seasonNumber: NowPlayingDtoSeasonNumber;
  episodeNumber: NowPlayingDtoEpisodeNumber;
  mediaType: string;
  progressPercent: NowPlayingDtoProgressPercent;
  paused: boolean;
  client: NowPlayingDtoClient;
  platform: string;
  startedAt: LocalDateTime;
}
