/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */
import type { TimeGranularity } from "./timeGranularity";
import type { TimePointDto } from "./timePointDto";

export interface PlaysOverTimeDto {
  granularity: TimeGranularity;
  points: TimePointDto[];
}
