/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */
import type { PostApiApplicationsBodyName } from "./postApiApplicationsBodyName";
import type { PostApiApplicationsBodyCategory } from "./postApiApplicationsBodyCategory";
import type { PostApiApplicationsBodyDescription } from "./postApiApplicationsBodyDescription";
import type { PostApiApplicationsBodyUrl } from "./postApiApplicationsBodyUrl";
import type { PostApiApplicationsBodyManagedBy } from "./postApiApplicationsBodyManagedBy";
import type { PostApiApplicationsBodyExternalId } from "./postApiApplicationsBodyExternalId";
import type { PostApiApplicationsBodyLogo } from "./postApiApplicationsBodyLogo";

export type PostApiApplicationsBody = {
  name: PostApiApplicationsBodyName;
  category: PostApiApplicationsBodyCategory;
  description: PostApiApplicationsBodyDescription;
  url: PostApiApplicationsBodyUrl;
  requiresVpn: boolean;
  managedBy: PostApiApplicationsBodyManagedBy;
  externalId: PostApiApplicationsBodyExternalId;
  logo: PostApiApplicationsBodyLogo;
};
