/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */
import type { ProblemMovieDtoYear } from "./problemMovieDtoYear";
import type { ProblemMovieDtoPosterUrl } from "./problemMovieDtoPosterUrl";

export interface ProblemMovieDto {
  radarrMovieId: number;
  title: string;
  year: ProblemMovieDtoYear;
  posterUrl: ProblemMovieDtoPosterUrl;
}
