/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */
import type { ProblemSeriesDtoYear } from "./problemSeriesDtoYear";
import type { ProblemSeriesDtoPosterUrl } from "./problemSeriesDtoPosterUrl";

export interface ProblemSeriesDto {
  sonarrSeriesId: number;
  title: string;
  year: ProblemSeriesDtoYear;
  posterUrl: ProblemSeriesDtoPosterUrl;
}
