/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */
import type { PutApiApplicationsIdBodyName } from "./putApiApplicationsIdBodyName";
import type { PutApiApplicationsIdBodyCategory } from "./putApiApplicationsIdBodyCategory";
import type { PutApiApplicationsIdBodyDescription } from "./putApiApplicationsIdBodyDescription";
import type { PutApiApplicationsIdBodyUrl } from "./putApiApplicationsIdBodyUrl";
import type { PutApiApplicationsIdBodyManagedBy } from "./putApiApplicationsIdBodyManagedBy";
import type { PutApiApplicationsIdBodyExternalId } from "./putApiApplicationsIdBodyExternalId";
import type { PutApiApplicationsIdBodyLogo } from "./putApiApplicationsIdBodyLogo";

export type PutApiApplicationsIdBody = {
  name: PutApiApplicationsIdBodyName;
  category: PutApiApplicationsIdBodyCategory;
  description: PutApiApplicationsIdBodyDescription;
  url: PutApiApplicationsIdBodyUrl;
  requiresVpn: boolean;
  managedBy: PutApiApplicationsIdBodyManagedBy;
  externalId: PutApiApplicationsIdBodyExternalId;
  logo: PutApiApplicationsIdBodyLogo;
};
