/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */
import type { QualitySliceDto } from "./qualitySliceDto";

export interface QualityBreakdownDto {
  resolutions: QualitySliceDto[];
  videoCodecs: QualitySliceDto[];
  audioCodecs: QualitySliceDto[];
  playbackMethods: QualitySliceDto[];
}
