/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */
import type { RadarrWebhookPayloadEventType } from "./radarrWebhookPayloadEventType";
import type { RadarrWebhookPayloadMovie } from "./radarrWebhookPayloadMovie";
import type { RadarrWebhookPayloadMovieFile } from "./radarrWebhookPayloadMovieFile";

export interface RadarrWebhookPayload {
  eventType?: RadarrWebhookPayloadEventType;
  movie?: RadarrWebhookPayloadMovie;
  movieFile?: RadarrWebhookPayloadMovieFile;
}
