/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */
import type { RadarrWebhookMovieId } from "./radarrWebhookMovieId";
import type { RadarrWebhookMovieTitle } from "./radarrWebhookMovieTitle";
import type { RadarrWebhookMovieYear } from "./radarrWebhookMovieYear";
import type { RadarrWebhookMovieImdbId } from "./radarrWebhookMovieImdbId";
import type { RadarrWebhookMovieTags } from "./radarrWebhookMovieTags";

export interface RadarrWebhookMovie {
  id?: RadarrWebhookMovieId;
  title?: RadarrWebhookMovieTitle;
  year?: RadarrWebhookMovieYear;
  imdbId?: RadarrWebhookMovieImdbId;
  tags?: RadarrWebhookMovieTags;
}
