/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */
import type { RecurringRuleRequestType } from "./recurringRuleRequestType";
import type { RecurringRuleRequestLabel } from "./recurringRuleRequestLabel";
import type { RecurringRuleRequestAmountCents } from "./recurringRuleRequestAmountCents";
import type { RecurringRuleRequestDayOfMonth } from "./recurringRuleRequestDayOfMonth";
import type { RecurringRuleRequestMemberId } from "./recurringRuleRequestMemberId";
import type { RecurringRuleRequestVendor } from "./recurringRuleRequestVendor";
import type { RecurringRuleRequestActive } from "./recurringRuleRequestActive";
import type { RecurringRuleRequestStartDate } from "./recurringRuleRequestStartDate";
import type { RecurringRuleRequestEndDate } from "./recurringRuleRequestEndDate";

export interface RecurringRuleRequest {
  type: RecurringRuleRequestType;
  label: RecurringRuleRequestLabel;
  amountCents: RecurringRuleRequestAmountCents;
  dayOfMonth: RecurringRuleRequestDayOfMonth;
  memberId: RecurringRuleRequestMemberId;
  vendor: RecurringRuleRequestVendor;
  active: RecurringRuleRequestActive;
  startDate: RecurringRuleRequestStartDate;
  endDate: RecurringRuleRequestEndDate;
}
