/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */
import type { Uuid } from "./uuid";
import type { EntryType } from "./entryType";
import type { RecurringRuleDtoMemberId } from "./recurringRuleDtoMemberId";
import type { RecurringRuleDtoVendor } from "./recurringRuleDtoVendor";
import type { LocalDate } from "./localDate";
import type { RecurringRuleDtoEndDate } from "./recurringRuleDtoEndDate";

export interface RecurringRuleDto {
  id: Uuid;
  type: EntryType;
  label: string;
  amountCents: number;
  dayOfMonth: number;
  memberId: RecurringRuleDtoMemberId;
  vendor: RecurringRuleDtoVendor;
  active: boolean;
  startDate: LocalDate;
  endDate: RecurringRuleDtoEndDate;
}
