/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */
import type { ScoreComponent } from "./scoreComponent";
import type { ScoreInputs } from "./scoreInputs";

export interface ScoreBreakdown {
  total?: number;
  components?: ScoreComponent[];
  inputs?: ScoreInputs;
}
