/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */
import type { ScoreInputsLastWatchedAt } from "./scoreInputsLastWatchedAt";
import type { ScoreInputsDownloadedAt } from "./scoreInputsDownloadedAt";
import type { ScoreInputsRequester } from "./scoreInputsRequester";

export interface ScoreInputs {
  lastWatchedAt?: ScoreInputsLastWatchedAt;
  downloadedAt?: ScoreInputsDownloadedAt;
  sizeBytes?: number;
  requester?: ScoreInputsRequester;
  correlation?: string;
}
