/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */
import type { SeerrWebhookPayloadNotificationType } from "./seerrWebhookPayloadNotificationType";
import type { SeerrWebhookPayloadEvent } from "./seerrWebhookPayloadEvent";
import type { SeerrWebhookPayloadSubject } from "./seerrWebhookPayloadSubject";
import type { SeerrWebhookPayloadMessage } from "./seerrWebhookPayloadMessage";
import type { SeerrWebhookPayloadIssue } from "./seerrWebhookPayloadIssue";
import type { SeerrWebhookPayloadComment } from "./seerrWebhookPayloadComment";
import type { SeerrWebhookPayloadExtra } from "./seerrWebhookPayloadExtra";

export interface SeerrWebhookPayload {
  notificationType?: SeerrWebhookPayloadNotificationType;
  event?: SeerrWebhookPayloadEvent;
  subject?: SeerrWebhookPayloadSubject;
  message?: SeerrWebhookPayloadMessage;
  issue?: SeerrWebhookPayloadIssue;
  comment?: SeerrWebhookPayloadComment;
  extra?: SeerrWebhookPayloadExtra;
}
