/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */
import type { SeerrWebhookCommentCommentMessage } from "./seerrWebhookCommentCommentMessage";
import type { SeerrWebhookCommentCommentedByUsername } from "./seerrWebhookCommentCommentedByUsername";

export interface SeerrWebhookComment {
  commentMessage?: SeerrWebhookCommentCommentMessage;
  commentedByUsername?: SeerrWebhookCommentCommentedByUsername;
}
