/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */
import type { SeerrWebhookIssueIssueId } from "./seerrWebhookIssueIssueId";
import type { SeerrWebhookIssueReportedByUsername } from "./seerrWebhookIssueReportedByUsername";

export interface SeerrWebhookIssue {
  issueId?: SeerrWebhookIssueIssueId;
  reportedByUsername?: SeerrWebhookIssueReportedByUsername;
}
