/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */
import type { SessionHistoryEntryDto } from "./sessionHistoryEntryDto";

export interface SessionHistoryPageDto {
  items: SessionHistoryEntryDto[];
  page: number;
  pageSize: number;
  totalPages: number;
  totalCount: number;
}
