/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */
import type { SessionHistoryEntryDtoSeriesName } from "./sessionHistoryEntryDtoSeriesName";
import type { SessionHistoryEntryDtoSeasonNumber } from "./sessionHistoryEntryDtoSeasonNumber";
import type { SessionHistoryEntryDtoEpisodeNumber } from "./sessionHistoryEntryDtoEpisodeNumber";
import type { LocalDateTime } from "./localDateTime";
import type { SessionHistoryEntryDtoProgressPercent } from "./sessionHistoryEntryDtoProgressPercent";
import type { SessionHistoryEntryDtoClient } from "./sessionHistoryEntryDtoClient";
import type { SessionHistoryEntryDtoDeviceName } from "./sessionHistoryEntryDtoDeviceName";
import type { SessionHistoryEntryDtoPlayMethod } from "./sessionHistoryEntryDtoPlayMethod";
import type { SessionHistoryEntryDtoVideoCodec } from "./sessionHistoryEntryDtoVideoCodec";
import type { SessionHistoryEntryDtoAudioCodec } from "./sessionHistoryEntryDtoAudioCodec";
import type { SessionHistoryEntryDtoResolution } from "./sessionHistoryEntryDtoResolution";

export interface SessionHistoryEntryDto {
  userName: string;
  itemName: string;
  seriesName: SessionHistoryEntryDtoSeriesName;
  seasonNumber: SessionHistoryEntryDtoSeasonNumber;
  episodeNumber: SessionHistoryEntryDtoEpisodeNumber;
  mediaType: string;
  startedAt: LocalDateTime;
  playDurationSeconds: number;
  progressPercent: SessionHistoryEntryDtoProgressPercent;
  completed: boolean;
  client: SessionHistoryEntryDtoClient;
  deviceName: SessionHistoryEntryDtoDeviceName;
  platform: string;
  playMethod: SessionHistoryEntryDtoPlayMethod;
  videoCodec: SessionHistoryEntryDtoVideoCodec;
  audioCodec: SessionHistoryEntryDtoAudioCodec;
  resolution: SessionHistoryEntryDtoResolution;
}
