/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */
import type { SonarrWebhookRelease } from "./sonarrWebhookRelease";

export type SonarrWebhookPayloadRelease = SonarrWebhookRelease | null;
