/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */
import type { SonarrWebhookSeriesId } from "./sonarrWebhookSeriesId";
import type { SonarrWebhookSeriesTitle } from "./sonarrWebhookSeriesTitle";
import type { SonarrWebhookSeriesYear } from "./sonarrWebhookSeriesYear";
import type { SonarrWebhookSeriesImdbId } from "./sonarrWebhookSeriesImdbId";
import type { SonarrWebhookSeriesTags } from "./sonarrWebhookSeriesTags";

export interface SonarrWebhookSeries {
  id?: SonarrWebhookSeriesId;
  title?: SonarrWebhookSeriesTitle;
  year?: SonarrWebhookSeriesYear;
  imdbId?: SonarrWebhookSeriesImdbId;
  tags?: SonarrWebhookSeriesTags;
}
