/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */
import type { SonarrWebhookPayloadEventType } from "./sonarrWebhookPayloadEventType";
import type { SonarrWebhookPayloadSeries } from "./sonarrWebhookPayloadSeries";
import type { SonarrWebhookPayloadEpisodes } from "./sonarrWebhookPayloadEpisodes";
import type { SonarrWebhookPayloadEpisodeFile } from "./sonarrWebhookPayloadEpisodeFile";
import type { SonarrWebhookPayloadRelease } from "./sonarrWebhookPayloadRelease";
import type { SonarrWebhookPayloadDownloadClient } from "./sonarrWebhookPayloadDownloadClient";

export interface SonarrWebhookPayload {
  eventType?: SonarrWebhookPayloadEventType;
  series?: SonarrWebhookPayloadSeries;
  episodes?: SonarrWebhookPayloadEpisodes;
  episodeFile?: SonarrWebhookPayloadEpisodeFile;
  release?: SonarrWebhookPayloadRelease;
  downloadClient?: SonarrWebhookPayloadDownloadClient;
}
