/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */
import type { SonarrWebhookEpisodeEpisodeNumber } from "./sonarrWebhookEpisodeEpisodeNumber";
import type { SonarrWebhookEpisodeSeasonNumber } from "./sonarrWebhookEpisodeSeasonNumber";
import type { SonarrWebhookEpisodeTitle } from "./sonarrWebhookEpisodeTitle";

export interface SonarrWebhookEpisode {
  episodeNumber?: SonarrWebhookEpisodeEpisodeNumber;
  seasonNumber?: SonarrWebhookEpisodeSeasonNumber;
  title?: SonarrWebhookEpisodeTitle;
}
