/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */
import type { SonarrWebhookReleaseIndexer } from "./sonarrWebhookReleaseIndexer";

export interface SonarrWebhookRelease {
  indexer?: SonarrWebhookReleaseIndexer;
}
