/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */
import type { StatisticsSummaryDtoPeakHour } from "./statisticsSummaryDtoPeakHour";

export interface StatisticsSummaryDto {
  totalWatchTimeSeconds: number;
  playCount: number;
  completedItems: number;
  peakHour: StatisticsSummaryDtoPeakHour;
}
