/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */

export type StatsPeriod = (typeof StatsPeriod)[keyof typeof StatsPeriod];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StatsPeriod = {
  TODAY: "TODAY",
  THIS_WEEK: "THIS_WEEK",
  THIS_MONTH: "THIS_MONTH",
  THIS_YEAR: "THIS_YEAR",
  ALL_TIME: "ALL_TIME",
} as const;
