/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */

export type TimeGranularity =
  (typeof TimeGranularity)[keyof typeof TimeGranularity];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TimeGranularity = {
  HOUR: "HOUR",
  DAY: "DAY",
  MONTH: "MONTH",
} as const;
