/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */
import type { TimelineEventDtoDetails } from "./timelineEventDtoDetails";
import type { LocalDateTime } from "./localDateTime";

export interface TimelineEventDto {
  id: number;
  eventType: string;
  title: string;
  details: TimelineEventDtoDetails;
  occurredAt: LocalDateTime;
}
