/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */

export type TopMediaSort = (typeof TopMediaSort)[keyof typeof TopMediaSort];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TopMediaSort = {
  NAME: "NAME",
  PLAYS: "PLAYS",
  WATCH_TIME: "WATCH_TIME",
  UNIQUE_VIEWERS: "UNIQUE_VIEWERS",
  COMPLETION_RATE: "COMPLETION_RATE",
  BINGE_SCORE: "BINGE_SCORE",
} as const;
