/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */
import type { TopMediaDtoCompletionRate } from "./topMediaDtoCompletionRate";
import type { TopMediaDtoBingeScore } from "./topMediaDtoBingeScore";

export interface TopMediaDto {
  name: string;
  plays: number;
  watchTimeSeconds: number;
  uniqueViewers: number;
  completionRate: TopMediaDtoCompletionRate;
  bingeScore: TopMediaDtoBingeScore;
}
