/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */

export interface TopUserDto {
  userName: string;
  watchTimeSeconds: number;
  itemsWatched: number;
  playCount: number;
}
