/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Homelab Manager API
 * OpenAPI spec version: 0.0.1
 */

export type TopWatchedPeriod =
  (typeof TopWatchedPeriod)[keyof typeof TopWatchedPeriod];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TopWatchedPeriod = {
  LastWeek: "LastWeek",
  LastMonth: "LastMonth",
  LastYear: "LastYear",
} as const;
