{{- if .Values.app.route.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "homelab-manager.fullname" . }}
  labels:
    {{- include "homelab-manager.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
  {{- with .Values.app.route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    {{- toYaml .Values.app.route.parentRefs | nindent 4 }}
  {{- with .Values.app.route.hostnames }}
  hostnames:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    - backendRefs:
        - name: {{ include "homelab-manager.fullname" . }}
          port: {{ .Values.app.service.port }}
{{- end }}
