package org.hoohoot.homelab.manager.infrastructure.matrix.bot.commands.regex

import com.trendyol.kediatr.*
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.params.ParameterizedTest
import org.junit.jupiter.params.provider.ValueSource

class DeadooMatrixCommandTest {
    @ParameterizedTest
    @ValueSource(
        strings = [
            "C'est comment ?",
            "C'est comment",
            "c'est comment",
            "Et sinon c'est comment ?",
            "c'est comment sinon ?",
            "deado",
            "DEADO",
            "deeeeeAAAAaaaaDDDdddOOOooo",
            "dddddeeeeeAAAADDooooDooo",
            "il est deado",
            "il est DDdeEEAAadoOOO",
            "défunt",
            "cadavre",
            "résurrection",
            "tombeau",
            "cercueil",
            "agonie",
            "euthanasie",
            "dépouille",
            "deuil",
            "décès",
            "meurtre",
            "suicide",
            "pendu",
            "ressusciter",
            "posthume",
            "exécution",
            "tombe",
            "funèbre",
            "cimetière",
            "disparu",
            "supplice",
            "immortalité",
            "mourir",
            "vivant",
            "assassinat",
            "enterrement",
            "faucheuse",
            "autopsie",
            "mortel",
            "mortuaire",
            "noyé",
            "trépas",
            "enfer",
            "funéraire",
            "blessé",
            "perte",
            "strangulation",
            "survivant",
            "crémation",
            "éternité",
            "glas",
            "pendaison",
            "tué",
            "claqué",
            "noyade",
            "destruction",
            "immortel",
            "catastrophe",
            "disparition",
            "meurtrier",
            "spiritisme",
            "tragique",
            "trépassé",
            "assassin",
            "Hadès",
            "paradis",
            "repos",
            "succession",
            "vieillesse",
            "corbillard",
            "dernier souffle",
            "extrême-onction",
            "funérailles",
            "funeste",
            "mourant",
            "bourreau",
            "fossoyeur",
            "inanimé",
            "macchabée",
            "mort-vivant",
            "Thanatos",
            "crevé",
            "désolation",
            "sépulture",
            "thanatologie",
            "enterré",
            "épitaphe",
            "porté disparu",
            "spectre",
            "taxidermie",
            "embaumement",
            "linceul",
            "martyr",
            "martyre",
            "matador",
            "métempsycose",
            "nécromancie",
            "Requiem",
            "vampire",
            "châtiment",
            "coroner",
            "dernier soupir",
            "guillotine",
            "mémoire",
            "néant",
            "poison",
            "sauver",
            "suicider",
            "apoptose",
            "évanoui",
            "infarctus du myocarde",
            "macabre",
            "nécrose",
            "survie",
            "torture",
            "assassiné",
            "bûcher",
            "canné",
            "désert",
            "échafaud",
            "fatigué",
            "foutu",
            "naze",
            "sépulcre",
            "chagrin",
            "charogne",
            "condamné",
            "crime",
            "empoisonnement",
            "mort-né",
            "proscription",
            "puni",
            "régicide",
            "six pieds sous terre",
            "victime",
            "violente",
            "cénotaphe",
            "cinéraire",
            "décédé",
            "ensevelissement",
            "gisant",
            "limbe",
            "maladie",
            "messe",
            "mortalité",
            "nuit",
            "peine capitale",
            "pendre",
            "regretter",
            "venger",
            "fosse",
            "gibet",
            "parque",
            "pécheur",
            "sommeil",
            "supplicié",
            "testament",
            "charnier",
            "commémoration",
            "danger",
            "ensevelir",
            "heure suprême",
            "prématurée",
            "purgatoire",
            "seuil",
            "veuve",
            "décapité",
            "étranglé",
            "menacer",
            "vie éternelle",
            "asphyxie",
            "Charon",
            "exécuter",
            "inerte",
            "post-mortem",
            "ruine",
            "achever",
            "anéantissement",
            "croque-mort",
            "crucifié",
            "crypte",
            "éteint",
            "exténué",
            "extinction",
            "fantôme",
            "morgue",
            "mors",
            "Nécrologie",
            "Odin",
            "péché",
            "pourriture",
            "Vallée de la mort",
            "attentat",
            "autre monde",
            "champ de bataille",
            "crématoire",
            "décapitation",
            "dernier adieu",
            "déterrer",
            "empoisonné",
            "génocide",
            "heure dernière",
            "inhumé",
            "intestat",
            "nécromasse",
            "nécrophile",
            "outre-tombe",
            "psychopompe",
            "regret",
            "repos éternel",
            "reste",
            "sarcophage",
            "suaire",
            "survivance",
            "valkyrie",
            "viatique",
            "accidentelle",
            "agonisant",
            "descente aux enfers",
            "douloureuse",
            "épuisé",
            "fin",
            "frôlé",
            "fusillade",
            "instantanée",
            "lente",
            "létal",
            "monument",
            "mortifère",
            "naissance",
            "nécrophilie",
            "oraison funèbre",
            "succéder",
            "suppression",
            "accident de la route",
            "atroces",
            "condamnation",
            "décimer",
            "délivrera",
            "élégie",
            "épouvante",
            "éternelle",
            "honorer",
            "incinération",
            "inhumation",
            "jonchée",
            "menace",
            "mort subite",
            "naufrage",
            "obsèques",
            "ossements",
            "peine",
            "pleurer",
            "présage",
            "souffrance",
            "surdose",
            "survenue",
            "terrible",
            "vaincu",
            "annoncée",
            "anticipée",
            "au-delà",
            "blessure",
            "coma",
            "condamnent",
            "cruel",
            "écroulement",
            "homicide",
            "horrible",
            "ignominie",
            "messager",
            "parricide",
            "sauveur",
            "tuant",
            "vengeance",
            "ankylosé",
            "apathique",
            "bienheureux",
            "bousillé",
            "brisé",
            "cassé",
            "chute",
            "conclusion",
            "décomposition",
            "défunction",
            "délavé",
            "dénouement",
            "mort",
            "morte"
        ]
    )
    fun `should match for c'est comment or deado`(input: String) {
        assertThat(DeadooMatrixCommand(FakeMediator()).matches(input)).isTrue()
    }
}

class FakeMediator : Mediator {
    override suspend fun <T : Notification> publish(notification: T) {
        TODO("Not yet implemented")
    }

    override suspend fun <T : Notification> publish(
        notification: T,
        publishStrategy: PublishStrategy
    ) {
        TODO("Not yet implemented")
    }

    override suspend fun <TCommand : Command> send(command: TCommand) {
        TODO("Not yet implemented")
    }

    override suspend fun <TCommand : CommandWithResult<TResult>, TResult> send(command: TCommand): TResult {
        TODO("Not yet implemented")
    }

    override suspend fun <TQuery : Query<TResponse>, TResponse> send(query: TQuery): TResponse {
        TODO("Not yet implemented")
    }
}