apiVersion: v2
name: homelab-manager
description: Homelab manager application and its Gateway API operator
type: application
version: 0.4.1-SNAPSHOT
appVersion: 0.4.1-SNAPSHOT
sources:
  - https://github.com/lucas-dclrcq/homelab-manager
