apiVersion: v2
name: homelab-manager
description: Homelab manager application and its Gateway API operator
type: application
version: 0.1.2
appVersion: 0.1.2
sources:
  - https://github.com/lucas-dclrcq/homelab-manager
