name: Build Custom Docker images

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - main

permissions:
  checks: write
  pull-requests: write

jobs:
  build:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      latest-sha: ${{ steps.docker_build.outputs.digest }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        name: Checkout

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@14487ce63c7a62a4a324b0bfb37086795e31c6c1 # v6
        with:
          context: .
          file: src/main/docker/Dockerfile.jvm
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/${{ github.repository_owner }}/homelab-manager:latest

  deploy:
    name: Deploy latest to homelab
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - name: Checkout GitOps Repo
        uses: actions/checkout@v4
        with:
          repository: lucas-dclrcq/homelabitty
          token: ${{ secrets.GH_PAT }}
          path: gitops-repo

      - name: Update HelmRelease File
        env:
          SHA256: ${{ needs.build.outputs.latest-sha }}
        run: |
          VERSION="latest@${SHA256}" yq eval '.spec.values.controllers.main.containers.main.image.tag = strenv(VERSION)' \
            -i gitops-repo/kubernetes/apps/default/homelab-manager/app/helmrelease.yaml

      - name: Commit & push new version
        env:
          SHA256: ${{ needs.build.outputs.latest-sha }}
        run: |
          cd gitops-repo
          git config user.name "Homelab Manager"
          git config user.email "homelab@manager.org"
          git add kubernetes/apps/default/homelab-manager/app/helmrelease.yaml
          git commit -m "chore(homelab-manager): update latest to ${SHA256}"
          git push origin main
